# [Key]   IMDB Keyword
# [Value] List of related MovieLens tags

# Keys with a * in front should do a wildcard regex search for "/key/"]
# Also see imdbIgnore at the bottom of this file.
imdbKeywords =
{
	#============================================ A =============================================
	"*9-11":["9/11"],
	"*abortion":["abortion"],
	"*action":["action", "action packed"],
	"*adventure":["adventure"],
	"*addiction":["addiction"],
	"drug-abuse":["addiction", "drug abuse", "drug addiction"],
	"prescription-drug-abuse":["addiction", "drug abuse", "drug addiction"],
	"substance-abuse":["addiction", "drug abuse", "drug addiction"],
	"*adolescen":["adolescence"],
	"*adopt":["adoption"],
	"*adulter":["adultery"],
	"cheating-wife":["adultery"],
	"cheating-husband":["adultery"],
	"africa":["africa"],
	"african":["africa"],
	"south-africa":["africa"],
	"north-africa":["africa"],
	"african-tribe":["africa"],
	"afterlife":["afterlife"],
	"belief-in-the-afterlife":["afterlife"],
	"ghost":["afterlife"],
	"heaven":["afterlife"],
	"hell":["afterlife"],
	"aging":["aging"],
	"rapid-aging":["aging"],
	"aids":["aids"],
	"hiv-aids":["aids"],
	"airplane":["airplane", "aviation"],
	"airplane-crash":["airplane"],
	"airplane-accident":["airplane"],
	"plane-crash":["airplane"],
	"airplane-pilot":["airplane", "aviation"],
	"airplane-trip":["airplane"],
	"*airport":["airport"],
	"*aviat":["aviation"],
	"*alaska",["alaska"],
	"*alcatraz":["alcatraz", "prison"],
	"*alcoholic":["alcoholism", "addiction"],
	"alcoholism":["alcoholism", "addiction"],
	"alcohol-abuse":["alcoholism", "addiction"],
	"*alien":["alien", "aliens", "alien invasion"],
	"alone":["alone in the world"],
	"last-man-on-earth":["alone in the world"],
	"*stranded":["alone in the world"],
	"deserted-island":["alone in the world"],
	"solitary-confinement":["alone in the world"],
	"amnesia":["amnesia"],
	"*robot":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"*cyborg":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"*android":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"animal":["animal", "animal movie"],
	"anthropomorphic-animal":["animal", "animal movie"],
	"talking-animal":["animal", "talking animals", "animal movie"],
	"human-animal-relationship":["animal", "animal movie"],
	"alternate-reality":["alternate reality", "alternate universe"],
	"alternative-reality":["alternate reality", "alternate universe"],
	"post-apocalypse":["apocalypse", "post apocalyptic", "post-apocalyptic"],
	"apocalypse":["post apocalyptic", "post-apocalyptic", "catastrophe"],
	"zombie-apocalypse":["apocalypse", "post apocalyptic", "post-apocalyptic", "zombie", "zombies"],
	"2d-animation":["animated", "animation", "cartoon"],
	"part-animation":["animated", "animation"],
	"stop-motion-animation":["animated", "animation"],
	"computer-animation":["animated", "animation", "computer animation"],
	"3d-animation":["animated", "animation", "computer animation", "cgi"],
	"animation-filmmaking":["animated", "animation"],
	"part-computer-animation":["animated", "animation", "computer animation", "cgi"],
	"clay-animation":["animated", "animation", "claymation"],
	"claymation":["animated", "animation", "claymation"],
	"cgi":["computer animation", "cgi"],
	"cgi-animation":["animated", "animation", "computer animation", "cgi"],
	"cgi-film":["computer animation", "cgi"],
	"*anime":["anime", "animated", "animation", "japan", "japanese"],
	"based-on-anime":["based on a tv show", "japan", "japanese"],
	"artificial-intelligence":["artificial intelligence"],
	"*arctic":["antarctica"],
	"anti-hero":["anti-hero"],
	"anti-heroine":["anti-hero"],
	"anti-semitism":["anti-semitism"],
	"*nazi":["anti-semitism"],
	"*world-war-two":["anti-semitism"],
	"*world-war-ii":["anti-semitism"],
	"*hitler":["anti-semitism"],
	"*anti-war":["anti-war"],
	"*archeolo":["archaeology"],
	"*assassin":["assassin", "assassins", "assassination"],
	"*astronaut":["astronauts"],
	"video-art":["art", "artist", "artistic", "artsy"],
	"performance-art":["art", "artist", "artistic", "artsy"],
	"modern-art":["art", "artist", "artistic", "artsy"],
	"abstract-art":["art", "artist", "artistic", "artsy"],
	"art-gallery":["art", "artist", "artistic", "artsy"],
	"art-museum":["art", "artist", "artistic", "artsy"],
	"art-film":["art", "artist", "artistic", "artsy", "art house"],
	"art-house":["art", "artist", "artistic", "artsy", "art house"],
	"art-exhibition":["art", "artist", "artistic", "artsy"],
	"art-dealer":["art", "artist", "artistic", "artsy"],
	"art-student":["art", "artist", "artistic", "artsy"],
	"art-class":["art", "artist", "artistic", "artsy"],
	"art-history":["art", "artist", "artistic", "artsy"],
	"art-school":["art", "artist", "artistic", "artsy"],
	"art-studio":["art", "artist", "artistic", "artsy"],
	"art-teacher":["art", "artist", "artistic", "artsy"],
	"art-collector":["art", "artist", "artistic", "artsy"],
	"art-critic":["art", "artist", "artistic", "artsy"],
	"art-show":["art", "artist", "artistic", "artsy"],
	"art-installation":["art", "artist", "artistic", "artsy"],
	"art-project":["art", "artist", "artistic", "artsy"],
	"artist":["art", "artist", "artistic", "artsy"],
	"painter":["art", "artist", "artistic", "artsy"],
	"painting":["art", "artist", "artistic", "artsy"],
	"sculptor":["art", "artist", "artistic", "artsy"],
	"*australia":["australian", "australia"],
	"*atheis":["atheism"],
	"*autis":["autism"],

	#============================================ B =============================================
	"b-movie":["bad acting", "bad", "cheesy", "corny", "unintentionally funny"],
	"b-horror":["bad acting", "bad", "cheesy", "corny", "unintentionally funny"],
	"b-western":["bad acting", "bad", "cheesy", "corny", "unintentionally funny"],
	"*baseball":["baseball"],
	"bank-robbery":["bank robbery"],
	"bank-robber":["bank robbery"],
	"*ballet":["ballet"],
	"based-on-novel":["based on a book", "adapted from:book", "based on book"],
	"based-on-book":["based on a book", "adapted from:book", "based on book"],
	"based-on-short-story":["based on a book", "adapted from:book", "based on book"],
	"based-on-story":["based on a book", "adapted from:book", "based on book"],
	"based-on-young-adult-novel":["based on a book", "adapted from:book", "based on book"],
	"based-on-poem":["based on a book", "adapted from:book", "based on book"],
	"based-on-fairy-tale":["based on a book", "adapted from:book", "based on book"],
	"based-on-folk-tale":["based on a book", "adapted from:book", "based on book"],
	"based-on-children's-book":["based on a book", "adapted from:book", "based on book", "kids", "children"],
	"based-on-comic-strip":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-comic-book":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-manga":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics", "japan", "japanese"],
	"based-on-comic":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-graphic-novel":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics", "based on a book", "adapted from:book", "based on book"],
	"based-on-game":["adapted from:game", "based on a video game", "computer game", "video game adaptation", "video game", "video games", "videogame"],
	"based-on-video-game":["adapted from:game", "based on a video game", "computer game", "video game adaptation", "video game", "video games", "videogame"],
	"based-on-stage-musical":["based on a play"],
	"based-on-play":["based on a play"],
	"based-on-opera":["based on a play"],
	"based-on-tv-series":["based on a tv show"],
	"based-on-tv-show":["based on a tv show"],
	"based-on-cartoon":["based on a tv show"],
	"based-on-live-action-tv-series":["based on a tv show"],
	"based-on-tv-movie":["based on a tv show"],
	"based-on-television-series":["based on a tv show"],
	"based-on-british-tv-series":["based on a tv show"],
	"based-on-true-story":["based on a true story", "based on true story"],
	"based-on-real-events":["based on a true story", "based on true story"],
	"based-on-true-events":["based on a true story", "based on true story"],
	"based-on-supposedly-true-story":["based on a true story", "based on true story"],
	"based-on-fact":["based on a true story", "based on true story"],
	"based-on-autobiography":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"based-on-biography":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"autobiography":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"based-on-real-person":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"biographical":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"biopic":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"*batman":["batman"],
	"*basketball":["basketball"],
	"*beatles":["beatles"],
	"beauty-contest":["beauty pageant"],
	"beauty-pageant":["beauty pageant"],
	"*pageant":["beauty pageant"],
	"*miss-america":["beauty pageant"],
	"beer":["beer", "drinking"],
	"beer-drinking":["beer", "drinking"],
	"alcohol":["beer", "drinking", "wine"],
	"alcoholic-drink":["beer", "drinking", "wine"],
	"*berlin":["berlin"],
	"*betray":["betrayal"],
	"*bibl":["christian", "christianity", "biblical"],
	"*bird":["birds"],
	"*bizarre":["bizarre", "weird"],
	"blaxploitation":["blaxploitation"],
	"blindness":["blindness"],
	"blind":["blindness"],
	"blind-man":["blindness"],
	"blind-woman":["blindness"],
	"blind-boy":["blindness"],
	"blind-girl":["blindness"],
	"*blood":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"*violen":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"gore":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"*bording-school":["boarding school"],
	"*boat":["boat"],
	"*cruise":["boat"],
	"*-ship":["boat"],
	"*bollywood":["bollywood"],
	"*bomb":["bombs"],
	"*bowling":["bowling"],
	"*boston":["boston"],
	"*brazil":["brazil"],
	"*brainwash":["brainwashing"],
	"*hypno":["brainwashing"],
	"black-and-white-scene":["black and white"],
	"black-and-white":["black and white"],
	"some-scenes-in-black-and-white":["black and white"],
	"black-comedy":["black comedy"],
	"black-humor":["black comedy"],
	"boxing":["boxing"],
	"kickboxing":["boxing"],
	"boxing-match":["boxing"],
	"boxing-ring":["boxing"],
	"boxing-gloves":["boxing"],
	"boxing-gym":["boxing"],
	"boxing-champion":["boxing"],
	"boxing-glove":["boxing"],
	"boxing-trainer":["boxing"],
	"boxing-training":["boxing"],
	"british-comedy":["british comedy"],
	"british-humor":["british comedy"],
	"*british":["british"],
	"*bbc":["british"],
	"*broadway":["broadway"],
	"two-brothers":["brothers"],
	"three-brothers":["brothers"],
	"brother-vs-brother":["brothers"],
	"brother-brother-relationship":["brothers"],
	"twin-brother":["brothers"],
	"brotherhood":["brothers"],
	"brother-in-law-brother-in-law-relationship":["brothers"],
	"half-brother-half-brother-relationship":["brothers"],
	"*abus":["brutal", "brutality", "torture"],
	"*brutal":["brutal", "brutality", "torture"],
	"*tortur":["brutal", "brutality", "torture"],
	"*buddy":["buddy movie"],
	"friendship":["buddy movie"],
	"friend":["buddy movie"],
	"best-friend":["buddy movie"],
	"*bully":["bullying"],
	"*business":["business"],
	"*corporation":["business"],

	#============================================ C =============================================
	"*california":["california"],
	"campfire":["camp"],
	"camp":["camp"],
	"camping":["camp"],
	"campy":["campy"],
	"*canad":["canada"],
	"*cannibal":["cannibalism"],
	"*cancer":["cancer"],
	"*capitalis":["capitalism"],
	"*car-chase":["car chase", "cars", "chase"],
	"automobile-chase":["car chase", "cars", "chase"],
	"motorcycle-chase":["car chase", "cars", "chase"],
	"car-motorcycle-chase":["car chase", "cars", "chase"],
	"police-chase":["car chase", "cars", "chase"],
	"car":["cars"],
	"*race-car":["cars"],
	"*racecar":["cars"],
	"streetcar":["cars"],
	"street-racing":["cars"],
	"*nascar":["cars"],
	"*truck":["cars"],
	"*cartoon":["cartoon"],
	"*casino":["casino", "gambling"],
	"*gambl":["casino", "gambling"],
	"*christian":["christian", "christianity"],
	"*christmas",["christmas"],
	"*circus",["circus"],
	"*comedy",["comedy", "humor"],
	"*humor",["comedy", "humor"]
	"clown":["circus"],
	"*clown":["clowns"],
	"*catastroph":["catastrophe"],
	"*disaster":["catastrophe"],
	"*catholic":["catholicism"],
	"censorship":["censorship"],
	"censor":["censorship"],
	"film-censorship":["censorship"],
	"film-censor":["censorship"],
	"censorship-board":["censorship"],
	"media-censorship":["censorship"],
	"censored":["censorship"],
	"cerebral":["cerebral"],
	"intellectual":["cerebral"],
	"pseudo-intellectual":["cerebral"],
	"*chase":["chase"],
	"*cheerlead":["cheerleading"],
	"*chess":["chess"],
	"*chicago":["chicago"],
	"chick-flick":["chick flick"],
	"*child-abuse":["child abuse"],
	"*childhood":["childhood", "children", "kids"],
	"children":["children", "kids"],
	"child":["children", "kids"],
	"child-protagonist":["children", "kids"],
	"*china":["china"],
	"*chocolate":["chocolate"],
	"cia-agent":["cia", "fbi"],
	"ex-cia-agent":["cia", "fbi"],
	"female-cia-agent":["cia", "fbi"],
	"cia":["cia", "fbi"],
	"secret-agent":["cia", "fbi"],
	"fbi-agent":["cia", "fbi"],
	"agent":["cia", "fbi"],
	"undercover-agent":["cia", "fbi"],
	"government-agent":["cia", "fbi"],
	"federal-agent":["cia", "fbi"],
	"secret-service-agent":["cia", "fbi"],
	"*cinemato":["cinematography"],
	"*filmmak":["cinematography"],
	"classic-car":["classic car", "cars"],
	"classical-music":["classical music"],
	"*claustro":["claustrophobic"],
	"*clon":["clones", "cloning"],
	"*college":["college"],
	"*university":["college"],
	"campus":["college"],
	"*fraternity":["college"],
	"*colonial":["colonialism"],
	"*coming-of-age":["coming of age", "coming-of-age"],
	"*communis":["communism"],
	"*competit":["competition"],
	"*tournament":["competition"],
	"*computer":["computers"],
	"arcade-game":["computer game", "video game", "video games", "videogame"],
	"computer-game":["computer game", "video game", "video games", "videogame"],
	"*video-game":["computer game", "video game", "video games", "videogame"],
	"con-artist":["con artists", "con men"],
	"con-man":["con artists", "con men"],
	"con-woman":["con artists", "con men"],
	"*confront":["confrontational"],
	"*conspiracy":["conspiracy", "conspiracy theory"],
	"*controversial":["controversial"],
	"*cook":["cooking"],
	"*corrupt":["corruption"],
	"courtroom":["court", "courtroom", "courtroom drama"],
	"court":["court", "courtroom", "courtroom drama"],
	"courthouse":["court", "courtroom", "courtroom drama"],
	"court-trial":["court", "courtroom", "courtroom drama"],
	"courtroom-drama":["court", "courtroom", "courtroom drama"],
	"court-hearing":["court", "courtroom", "courtroom drama"],
	"supreme-court":["court", "courtroom", "courtroom drama"],
	"court-case":["court", "courtroom", "courtroom drama"],
	"courage":["courage"],
	"creativity":["creativity"],
	"creative-process":["creativity"],
	"*horror":["creepy", "scary", "horror"],
	"*creepy":["creepy", "scary", "horror"],
	"*spooky":["creepy", "scary", "horror"],
	"*crime":["crime"],
	"*cross-dress":["cross dressing"],
	"crude-humor":["crude humor", "dark humor"],
	"dark-humor":["crude humor", "dark humor"],
	"*cuba":["cuba"],
	"cult-film":["cult film", "cult classic", "classic"],
	"cult-tv":["cult film", "cult classic", "classic"],
	"cult":["cult"],
	"culture-clash":["culture clash"],
	"culture-shock":["culture clash"],
	"cyberpunk":["cyberpunk"],
	"*cynic":["cynical"],

	#============================================ D =============================================

	#============================================ E =============================================

	#============================================ F =============================================
	"ice-skating":["figure skating"],
	"figure-skating":["figure skating"],
	"*fight":["fight scenes", "fighting", "action", "action packed"],
	"fight-the-system":["fighting the system"],
	"*rebellion":["fighting the system"],
	"*protest":["fighting the system"],

	#============================================ G =============================================

	#============================================ H =============================================

	#============================================ I =============================================

	#============================================ J =============================================
	"*james-bond":["james bond"],
	"*jane-austen":["jane austen"],
	"*japan":["japan", "japanese"],
	"*jazz":["jazz"],
	"*jesus":["jesus", "christian", "christianity", "biblical"],
	"judaism":["jewish", "jews", "judaism"],
	"rabbi":["jewish", "jews", "judaism"],
	"*mitzvah":["jewish", "jews", "judaism"],
	"*jewish":["jewish", "jews", "judaism"],
	"*journalis":["journalism"],
	"*reporter":["journalism"],
	"*jungle":["jungle"],
	"*rain-forest":["jungle"],
	"*rainforest":["jungle"],
	"justice":["justice"],
	"*-justice":["justice"],

	#============================================ K =============================================
	"*kidnap":["kidnapping", "hostage"],
	"*hostage":["kidnapping", "hostage"],
	"family-relationship":["kids and family", "family", "family bonds"],
	"*king-arthur":["king arthur"],
	"*excalibur":["king arthur"],
	"*kung-":["kung fu", "fight scenes", "fighting", "action", "action packed"],
	"*karate":["kung fu", "fight scenes", "fighting", "action", "action packed"],
	"*martial-":["kung fu", "fight scenes", "fighting", "action", "action packed"],
	"*kurosawa":["kurosawa", "japan", "japanese"],

	#============================================ L =============================================

	#============================================ M =============================================

	#============================================ N =============================================

	#============================================ O =============================================

	#============================================ P =============================================

	#============================================ Q =============================================
	"*queer":["queer", "gay", "gay character", "homosexuality"],
	"*gay":["queer", "gay", "gay character", "homosexuality"],
	"*homosexual":["queer", "gay", "gay character", "homosexuality"],
	"*quirk":["quirky"],

	#============================================ R =============================================

	#============================================ S =============================================

	#============================================ T =============================================

	#============================================ U =============================================
	"undercover-cop":["undercover cop"],
	"undercover-police":["undercover cop"],
	"undercover-policeman":["undercover cop"],
	"undercover-policewoman":["undercover cop"],
	"*underdog":["underdog"],
	"*underwater":["underwater"],
	"*united-nations":["united nations"],
	"american-history":["us history"],
	"*utopia":["utopia"],

	#============================================ V =============================================
	"virtual-reality":["virtual reality"],
	"virtual-set":["virtual reality"],
	"virtuality":["virtual reality"],
	"virtual-world":["virtual reality"],
	"virtual":["virtual reality"],
	"virtual-reality-game":["virtual reality", "computer game", "video game", "video games", "videogame"],
	"virtual-life":["virtual reality"],
	"*vampire":["vampire", "vampires"],
	"*dracula":["vampire", "vampires"],
	"vampire-human-love":["vampire human love"],
	"vengeance":["vengeance"],
	"revenge":["vengeance"],
	"vienna-austria":["vienna"],
	"vietnam":["vietnam"],
	"vietnamese":["vietnam"],
	"*vigilant":["vigilante", "vigilantism", "justice"],
	"*virus":["virus"],
	"infection":["virus"],
	"*plague":["virus"],
	"*epidemic":["virus"],
	"*pandemic":["virus"],
	"contagious-disease":["virus"],
	"*contagious":["virus"],
	"*virgin":["virginity"],
	"*voodoo":["voodoo"],
	"black-magic":["voodoo"],
	"*witchcraft":["voodoo"],
	"*curse":["voodoo"],
	"*voyeur":["voyeurism"],

	#============================================ W =============================================
	"*army":["war", "war movie", "wartime"],
	"*soldier":["war", "war movie", "wartime"],
	"world-war-two":["war", "war movie", "wartime", "wwii", "world war ii"],
	"world-war-one":["war", "war movie", "wartime", "world war i"],
	"war-veteran":["war", "war movie", "wartime"],
	"war-hero":["war", "war movie", "wartime"],
	"war-violence":["war", "war movie", "wartime"],
	"war-crime":["war", "war movie", "wartime"],
	"cold-war-era":["war", "war movie", "wartime", "cold war"],
	"war-criminal":["war", "war movie", "wartime"],
	"war-on-terrorism":["war", "war movie", "wartime"],
	"world-war-three":["war", "war movie", "wartime"],
	"war-zone":["war", "war movie", "wartime"],
	"war-for-independence":["war", "war movie", "wartime"],
	"war-memorial":["war", "war movie", "wartime"],
	"war-on-terror":["war", "war movie", "wartime"],
	"war-filmmaking":["war", "war movie", "wartime"],
	"war-aftermath":["war", "war movie", "wartime"],
	"war-footage":["war", "war movie", "wartime"],
	"*civil-war":["war", "war movie", "wartime", "civil war"],
	"cold-war":["war", "war movie", "wartime", "cold war"],
	"prisoner-of-war":["war", "war movie", "wartime"],
	"*vietnam-war":["war", "war movie", "wartime", "vietnam war"],
	"vietnam-veteran":["war", "war movie", "wartime", "vietnam war"],
	"vietnam-vet":["war", "war movie", "wartime", "vietnam war"],
	"vietnam-flashback":["war", "war movie", "wartime", "vietnam war"],
	"vietnam-memorial":["war", "war movie", "wartime", "vietnam war"],
	"vietnamese-soldier":["war", "war movie", "wartime", "vietnam war"],
	"american-civil-war":["war", "war movie", "wartime", "american civil war"],
	"iraq-war":["war", "war movie", "wartime"],
	"korean-war":["war", "war movie", "wartime"],
	"nuclear-war":["war", "war movie", "wartime"],
	"spanish-american-war":["war", "war movie", "wartime"],
	"indian-war":["war", "war movie", "wartime"],
	"napoleonic-wars":["war", "war movie", "wartime"],
	"weapon":["weapons"],
	"*wedding":["wedding"],
	"weed":["weed", "drugs", "marijuana"],
	"smoking-weed":["weed", "drugs", "marijuana"],
	"*marijuana":["weed", "drugs", "marijuana"],
	"*cocaine":["weed", "drugs", "marijuana"],
	"methamphetamine":["weed", "drugs", "marijuana"],
	"crystal-meth":["weed", "drugs", "marijuana"],
	"meth":["weed", "drugs", "marijuana"],
	"meth-lab":["weed", "drugs", "marijuana"],
	"heroin":["weed", "drugs", "marijuana"],
	"*heroin-":["weed", "drugs", "marijuana"],
	"*drug":["weed", "drugs", "marijuana"],
	"*werewolf":["werewolf", "werewolves"],
	"spaghetti-western":["western"],
	"western-town":["western"],
	"western-hero":["western"],
	"modern-western":["western"],
	"neo-western":["western"],
	"space-western":["western"],
	"*witch":["witch", "witches"],
	"*wizard":["wizards"],
	"*working-class":["working class"],
	"*workplace":["workplace"],
	"*politic":["world politics", "political", "politics"],
	"*writer":["writers", "writing", "writer's life"],

	#============================================ Z =============================================
	"*zombie":["zombie", "zombies"]
}


# IMDB Keywords that should be ignored while processing the given wildcard filters.
# Values with a * in front should ignore all keywords that contain that value as a substring.
imdbIgnore = {
	"*abus":["substance-abuse", "alcohol-abuse", "drug-abuse", "prescription-drug-abuse", "abuse-of-power"]
	"*alien":["illegal-alien"],
	"*autis":["flautist"],
	"*aviat":["aviator-sunglasses", "la-traviata", "reference-to-la-traviata"],
	"*berlin":["oberlin", "reference-to-frederick-george-abberline", "irving-berlin", "reference-to-irving-berlin"],
	"*buddy":["reference-to-buddy-holly", "reference-to-buddy-ebsen", "reference-to-buddy-hackett", "reference-to-buddy-rich"],
	"*chess":["*duchess"],
	"*cruise":["*cruise-missle", "toyota-landcruiser", "chrysler-pt-cruiser", "reference-to-tom-cruise"],
	"*-ship":["space-ship", "rocket-ship", "gold-shipment", "flying-ship", "alien-ship"],
	"*christian":["hans-christian-andersen"],
	"*clon":["*cyclon", "insection-clone", "batman-clone", "mortal-combat-clone", "clonskeagh-dublin", "doom-clone", "leisure-suit-larry-clone", "tex-murphy-clone", "reference-to-saint-brendan-the-navigator-of-clonfert"]
	"*computer":["*computer-animat"],
	"*cook":["*cookie"],
	"*creepy":["creepy-crawlie"],
	"*cuba":["*scuba", "*incubat"],
	"*curse":["curse-word"],
	"*drug":["drugstore"],
	"*hypno":["rohypnol"],
	"*horror":["b-horror"],
	"*fight":["firefighter", "fighter-jet", "food-fight", "fighter-pilot", "dogfight", "pillow-fight", "fire-fight", "fight-the-system", "bullfight", "bullfighting", "cockfight", "snowball-fight"],
	"*jazz":["jazz-the-character"],
	"*jewish":["jewish-stereotype", "jewish-slur"],
	"*protest":["*protestant"],
	"*robot":["ostrobothnia-finland"],
	"*witch":["*switch", "*twitch"],
	"*virgin":["*virginia", "*virgin-mary"]
}