# [Key]   IMDB Keyword
# [Value] List of related MovieLens tags

# To determine which movies should have the MovieLens tags appended:
# 		- Default query on the IMDB db would be {"keywords":"key"}
# 		- Keys with a * in front should query the IMDB database for {"keywords":/key/}
# 		- Keys containing a : character (ie "0:1") should query the IMDB database for {"0":1}
#
# Also see imdbIgnore at the bottom of this file.

imdbKeywords = {
	#============================================ 0-9 =============================================
	"18th-century":["18th century"],
	"eighteenth-century":["18th century"],
	"19th-century":["19th century"],
	"nineteenth-century":["19th century"],
	"1920s":["1920s"],
	"1930s":["1930s"],
	"1950s":["1950s"],
	"1960s":["1960s"],
	"1970s":["1970s"],
	"1980s":["1980s", "80s"],
	"$and:[{'year':{'$gte':'1920'}},{'year':{'$lt':'1930'}}]":["1920s"],
	"$and:[{'year':{'$gte':'1930'}},{'year':{'$lt':'1940'}}]":["1930s"],
	"$and:[{'year':{'$gte':'1950'}},{'year':{'$lt':'1960'}}]":["1950s"],
	"$and:[{'year':{'$gte':'1960'}},{'year':{'$lt':'1970'}}]":["1960s"],
	"$and:[{'year':{'$gte':'1970'}},{'year':{'$lt':'1980'}}]":["1970s"],
	"$and:[{'year':{'$gte':'1980'}},{'year':{'$lt':'1990'}}]":["1980s", "80s"],
	"70mm-film":["70mm"],
	"*9-11":["9/11"],

	#============================================ A =============================================
	"companies:'Aardman Animations'":["aardman", "aardman studios", "computer animation", "claymation"],
	"*abortion":["abortion"],
	"*action":["action", "action packed"],
	"genre:'Action'":["action", "action packed"],
	"*adventure":["adventure"],
	"genre:'Adventure'":["adventure"],
	"*addiction":["addiction"],
	"drug-abuse":["addiction", "drug abuse", "drug addiction"],
	"prescription-drug-abuse":["addiction", "drug abuse", "drug addiction"],
	"substance-abuse":["addiction", "drug abuse", "drug addiction"],
	"*adolescen":["adolescence"],
	"*adopt":["adoption"],
	"*adulter":["adultery", "infidelity"],
	"*infidelity":["adultery", "infidelity"],
	"cheating-wife":["adultery", "infidelity"],
	"cheating-husband":["adultery", "infidelity"],
	"africa":["africa"],
	"african":["africa"],
	"north-africa":["africa"],
	"african-tribe":["africa"],
	"afterlife":["afterlife", "ghosts/afterlife", "life & death"],
	"life-after-death":["afterlife", "ghosts/afterlife", "life & death"],
	"belief-in-the-afterlife":["afterlife", "ghosts/afterlife"],
	"ghost":["afterlife", "ghosts", "ghosts/afterlife"],
	"heaven":["afterlife"],
	"hell":["afterlife"],
	"aging":["aging"],
	"rapid-aging":["aging"],
	"aids":["aids"],
	"hiv-aids":["aids"],
	"airplane":["airplane", "aviation"],
	"airplane-crash":["airplane"],
	"airplane-accident":["airplane"],
	"plane-crash":["airplane"],
	"airplane-pilot":["airplane", "aviation"],
	"airplane-trip":["airplane"],
	"*airport":["airport"],
	"*aviat":["aviation"],
	"*alaska":["alaska"],
	"*alcatraz":["alcatraz", "prison"],
	"*alcoholic":["alcoholism", "addiction"],
	"alcoholism":["alcoholism", "addiction"],
	"alcohol-abuse":["alcoholism", "addiction"],
	"*alien":["alien", "aliens", "alien invasion"],
	"alone":["alone in the world", "isolation", "loneliness", "solitude"],
	"last-man-on-earth":["alone in the world", "isolation", "loneliness", "solitude"],
	"lone-survivor":["alone in the world", "isolation", "loneliness", "solitude"],
	"sole-survivor":["alone in the world", "isolation", "loneliness", "solitude"],
	"last-survivor":["alone in the world", "isolation", "loneliness", "solitude"],
	"*stranded":["alone in the world", "isolation", "stranded", "solitude"],
	"deserted-island":["alone in the world", "isolation", "stranded", "island", "solitude"],
	"solitary-confinement":["alone in the world", "isolation", "loneliness", "solitude"],
	"*isolat":["alone in the world", "loneliness", "isolation", "solitude"],
	"solitude":["alone in the world", "isolation", "loneliness", "solitude"],
	"solitary":["alone in the world", "isolation", "loneliness", "solitude"],
	"amnesia":["amnesia", "memory loss"],
	"memory-loss":["amnesia", "memory loss"],
	"loss-of-memory":["amnesia", "memory loss"],
	"*robot":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"*cyborg":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"*android":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"animal":["animal", "animal movie"],
	"anthropomorphic-animal":["animal", "animal movie"],
	"talking-animal":["animal", "talking animals", "animal movie"],
	"human-animal-relationship":["animal", "animal movie"],
	"alternate-reality":["alternate reality", "alternate universe"],
	"alternative-reality":["alternate reality", "alternate universe"],
	"post-apocalypse":["apocalypse", "post apocalyptic", "post-apocalyptic"],
	"apocalypse":["post apocalyptic", "post-apocalyptic", "catastrophe", "disaster", "end of the world"],
	"*end-of-the-world":["post apocalyptic", "post-apocalyptic", "catastrophe", "disaster", "end of the world"],
	"zombie-apocalypse":["apocalypse", "post apocalyptic", "post-apocalyptic", "zombie", "zombies"],
	"genres:'Animation'":["animated", "animation"],
	"2d-animation":["animated", "animation", "cartoon"],
	"part-animation":["animated", "animation"],
	"stop-motion-animation":["animated", "animation"],
	"computer-animation":["animated", "animation", "computer animation"],
	"*3d":["3d"],
	"3d-animation":["animated", "animation", "computer animation", "cgi", "3d"],
	"animation-filmmaking":["animated", "animation"],
	"part-computer-animation":["animated", "animation", "computer animation", "cgi"],
	"clay-animation":["animated", "animation", "claymation"],
	"claymation":["animated", "animation", "claymation"],
	"cgi":["computer animation", "cgi", "effects", "special effects"],
	"cgi-animation":["animated", "animation", "computer animation", "cgi"],
	"cgi-film":["computer animation", "cgi"],
	"*anime":["anime", "animated", "animation", "japan", "japanese"],
	"artificial-intelligence":["artificial intelligence"],
	"*arctic":["antarctica"],
	"anti-hero":["anti-hero"],
	"anti-heroine":["anti-hero"],
	"anti-semitism":["anti-semitism"],
	"*nazi":["anti-semitism", "nazi", "nazis"],
	"*world-war-two":["anti-semitism", "nazi", "nazis"],
	"*world-war-ii":["anti-semitism", "nazi", "nazis"],
	"*hitler":["anti-semitism", "holocaust", "nazi", "nazis"],
	"*holocaust":["anti-semitism", "holocaust", "nazi", "nazis"],
	"*concentration-camp":["holocaust", "nazi", "nazis"],
	"*anti-war":["anti-war"],
	"*archeolo":["archaeology"],
	"*assassin":["assassin", "assassins", "assassination", "hit men", "hitman", "murder", "death"],
	"*hitman":["assassin", "assassins", "assassination", "hit men", "hitman", "murder", "death"],
	"*astronaut":["astronauts", "space", "space travel", "space program"],
	"video-art":["art", "artist", "artistic", "artsy"],
	"performance-art":["art", "artist", "artistic", "artsy"],
	"modern-art":["art", "artist", "artistic", "artsy"],
	"abstract-art":["art", "artist", "artistic", "artsy"],
	"art-gallery":["art", "artist", "artistic", "artsy"],
	"art-museum":["art", "artist", "artistic", "artsy"],
	"art-film":["art", "artist", "artistic", "artsy", "art house"],
	"art-house":["art", "artist", "artistic", "artsy", "art house"],
	"art-exhibition":["art", "artist", "artistic", "artsy"],
	"art-dealer":["art", "artist", "artistic", "artsy"],
	"art-student":["art", "artist", "artistic", "artsy"],
	"art-class":["art", "artist", "artistic", "artsy"],
	"art-history":["art", "artist", "artistic", "artsy"],
	"art-school":["art", "artist", "artistic", "artsy"],
	"art-studio":["art", "artist", "artistic", "artsy"],
	"art-teacher":["art", "artist", "artistic", "artsy"],
	"art-collector":["art", "artist", "artistic", "artsy"],
	"art-critic":["art", "artist", "artistic", "artsy"],
	"art-show":["art", "artist", "artistic", "artsy"],
	"art-installation":["art", "artist", "artistic", "artsy"],
	"art-project":["art", "artist", "artistic", "artsy"],
	"artist":["art", "artist", "artistic", "artsy"],
	"painter":["art", "artist", "artistic", "artsy"],
	"painting":["art", "artist", "artistic", "artsy"],
	"sculptor":["art", "artist", "artistic", "artsy"],
	"*australia":["australian", "australia"],
	"country:'Australia'":["australia", "australian"],
	"*atheis":["atheism"],
	"*autis":["autism"],
	"*almodovar":["almodovar"],
	"crew:'Pedro Almodóvar'":["almodovar"],
	"cast:'Amy Smart'":["amy smart"],
	"*arnold-schwarzenegger":["arnold"],
	"cast:'Arnold Schwarzenegger'":["arnold"],

	#============================================ B =============================================
	"b-movie":["bad acting", "bad", "cheesy", "corny", "unintentionally funny", "so bad it's funny", "so bad it's good"],
	"b-horror":["bad acting", "bad", "cheesy", "corny", "unintentionally funny", "so bad it's funny", "so bad it's good"],
	"b-western":["bad acting", "bad", "cheesy", "corny", "unintentionally funny", "so bad it's funny", "so bad it's good"],
	"*baseball":["baseball"],
	"bank-robbery":["bank robbery", "robbery", "heist"],
	"bank-robber":["bank robbery", "robbery", "heist"],
	"*ballet":["ballet"],
	"based-on-novel":["based on a book", "adapted from:book", "based on book", "literary adaptation"],
	"based-on-book":["based on a book", "adapted from:book", "based on book", "literary adaptation"],
	"based-on-short-story":["based on a book", "adapted from:book", "based on book", "literary adaptation"],
	"based-on-story":["based on a book", "adapted from:book", "based on book", "literary adaptation"],
	"based-on-young-adult-novel":["based on a book", "adapted from:book", "based on book", "literary adaptation"],
	"based-on-poem":["based on a book", "adapted from:book", "based on book", "literary adaptation"],
	"based-on-fairy-tale":["fairy tale", "fairy tales", "based on a book", "adapted from:book", "based on book"],
	"based-on-folk-tale":["based on a book", "adapted from:book", "based on book", "mythology"],
	"based-on-children's-book":["based on a book", "adapted from:book", "based on book", "kids", "children", "literary adaptation"],
	"based-on-comic-strip":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-comic-book":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-manga":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics", "japan", "japanese"],
	"based-on-comic":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-graphic-novel":["graphic novel", "adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics", "based on a book", "adapted from:book", "based on book"],
	"based-on-game":["adapted from:game", "based on a video game", "computer game", "video game adaptation", "video game", "video games", "videogame"],
	"based-on-video-game":["adapted from:game", "based on a video game", "computer game", "video game adaptation", "video game", "video games", "videogame"],
	"based-on-stage-musical":["based on a play", "musical"],
	"based-on-play":["based on a play"],
	"based-on-opera":["based on a play"],
	"based-on-tv-series":["based on a tv show"],
	"based-on-tv-show":["based on a tv show"],
	"based-on-anime":["based on a tv show"],
	"based-on-cartoon":["based on a tv show"],
	"based-on-live-action-tv-series":["based on a tv show"],
	"based-on-tv-movie":["based on a tv show"],
	"based-on-television-series":["based on a tv show"],
	"based-on-british-tv-series":["based on a tv show"],
	"based-on-true-story":["based on a true story", "based on true story"],
	"based-on-real-events":["based on a true story", "based on true story"],
	"based-on-true-events":["based on a true story", "based on true story"],
	"based-on-supposedly-true-story":["based on a true story", "based on true story"],
	"based-on-fact":["based on a true story", "based on true story"],
	"based-on-autobiography":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"based-on-biography":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"autobiography":["based on a true story", "based on true story", "factual", "biographical", "biography", "biopic", "true story"],
	"based-on-real-person":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"biographical":["based on a true story", "based on true story", "factual", "biographical", "biography", "biopic", "true story"],
	"biopic":["based on a true story", "based on true story", "factual", "biographical", "biography", "biopic", "true story"],
	"genres:'Biography'":["based on a true story", "based on true story", "factual", "biographical", "biography", "biopic", "true story"],
	"*batman":["batman"],
	"*basketball":["basketball"],
	"*beatles":["beatles"],
	"beauty-contest":["beauty pageant", "fashion"],
	"beauty-pageant":["beauty pageant", "fashion"],
	"*pageant":["beauty pageant", "fashion"],
	"*miss-":["beauty pageant", "fashion"],
	"*fashion-show":["beauty pageant", "fashion"],
	"beer":["beer", "drinking"],
	"beer-drinking":["beer", "drinking"],
	"alcohol":["beer", "drinking", "wine"],
	"alcoholic-drink":["beer", "drinking", "wine"],
	"*berlin":["berlin", "german", "germany"],
	"*betray":["betrayal"],
	"*bibl":["christian", "christianity", "biblical"],
	"*bird":["birds"],
	"*bizarre":["bizarre", "weird"],
	"blaxploitation":["blaxploitation"],
	"blindness":["blindness"],
	"blind":["blindness"],
	"blind-man":["blindness"],
	"blind-woman":["blindness"],
	"blind-boy":["blindness"],
	"blind-girl":["blindness"],
	"*blood":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"*violen":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"gore":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"*bording-school":["boarding school"],
	"*boat":["boat"],
	"*cruise":["boat"],
	"*-ship":["boat"],
	"*bollywood":["bollywood", "india"],
	"country:'India'":["bollywood", "india"],
	"*bomb":["bombs"],
	"*bowling":["bowling"],
	"bowler":["bowling"],
	"*boston":["boston"],
	"*brazil":["brazil"],
	"country:'Brazil'":["brazil"],
	"*brainwash":["brainwashing"],
	"*hypno":["brainwashing"],
	"black-and-white-scene":["black and white"],
	"black-and-white":["black and white"],
	"some-scenes-in-black-and-white":["black and white"],
	"black-comedy":["black comedy"],
	"black-humor":["black comedy"],
	"boxing":["boxing"],
	"kickboxing":["boxing"],
	"boxing-match":["boxing"],
	"boxing-ring":["boxing"],
	"boxing-gloves":["boxing"],
	"boxing-gym":["boxing"],
	"boxing-champion":["boxing"],
	"boxing-glove":["boxing"],
	"boxing-trainer":["boxing"],
	"boxing-training":["boxing"],
	"british-comedy":["british comedy"],
	"british-humor":["british comedy"],
	"*british":["british"],
	"*bbc":["british"],
	"country:'UK'":["british"],
	"*broadway":["broadway"],
	"*brothers":["brothers"],
	"brother-vs-brother":["brothers"],
	"*brother-brother":["brothers"],
	"*brother-in-law-brother-in-law":["brothers"],
	"*half-brother-half-brother":["brothers"],
	"*abus":["brutal", "brutality", "torture"],
	"*brutal":["brutal", "brutality", "torture"],
	"*tortur":["brutal", "brutality", "torture"],
	"*buddy":["buddy movie", "friendship"],
	"friendship":["buddy movie", "friendship"],
	"friend":["buddy movie", "friendship"],
	"best-friend":["buddy movie", "friendship"],
	"*bully":["bullying"],
	"*school-tormentor":["bullying"],
	"*business":["business"],
	"*corporation":["business"],

	#============================================ C =============================================
	"*california":["california"],
	"campfire":["camp"],
	"camp":["camp"],
	"camping":["camp"],
	"campy":["campy"],
	"*canad":["canada"],
	"country:'Canada'":["canada"],
	"*cannibal":["cannibalism"],
	"*cancer":["cancer"],
	"*capitalis":["capitalism"],
	"*car-chase":["car chase", "cars", "chase"],
	"automobile-chase":["car chase", "cars", "chase"],
	"motorcycle-chase":["car chase", "cars", "chase"],
	"car-motorcycle-chase":["car chase", "cars", "chase"],
	"police-chase":["car chase", "cars", "chase"],
	"car":["cars"],
	"*race-car":["cars"],
	"*racecar":["cars"],
	"streetcar":["cars"],
	"street-racing":["cars"],
	"*nascar":["cars"],
	"*truck":["cars"],
	"*cartoon":["cartoon"],
	"*casino":["casino", "gambling"],
	"*gambl":["gambling"],
	"*christian":["christian", "christianity"],
	"*christmas":["christmas"],
	"*circus":["circus"],
	"*trapeze":["circus"],
	"*comedy":["comedy", "humor", "funny", "humorous", "hillarious", "hilarious"],
	"*humor":["comedy", "humor", "funny", "humorous", "hillarious", "hilarious"],
	"genre:'Comedy'":["comedy", "humor", "funny", "humorous", "hillarious", "hilarious"],
	"clown":["circus"],
	"*clown":["clowns"],
	"*catastroph":["catastrophe", "disaster"],
	"*disaster":["catastrophe", "disaster"],
	"*catholic":["catholicism"],
	"censorship":["censorship"],
	"censor":["censorship"],
	"film-censorship":["censorship"],
	"film-censor":["censorship"],
	"censorship-board":["censorship"],
	"media-censorship":["censorship"],
	"censored":["censorship"],
	"cerebral":["cerebral", "intellectual", "thought-provoking"],
	"intellectual":["cerebral", "intellectual", "thought-provoking"],
	"pseudo-intellectual":["cerebral", "intellectual", "thought-provoking"],
	"*chase":["chase"],
	"*cheerlead":["cheerleading"],
	"*chess":["chess"],
	"*chicago":["chicago"],
	"chick-flick":["chick flick", "girlie movie"],
	"*child-abuse":["child abuse"],
	"*childhood":["childhood", "children", "kids"],
	"children":["children", "kids"],
	"child":["children", "kids"],
	"child-protagonist":["children", "kids"],
	"*china":["china"],
	"country:'China'":["china"],
	"*chocolate":["chocolate"],
	"cia-agent":["cia", "fbi", "secret service"],
	"ex-cia-agent":["cia", "fbi", "secret service"],
	"female-cia-agent":["cia", "fbi", "secret service"],
	"cia":["cia", "fbi", "secret service"],
	"secret-agent":["cia", "fbi", "secret service"],
	"fbi-agent":["cia", "fbi", "secret service"],
	"agent":["cia", "fbi", "secret service"],
	"undercover-agent":["cia", "fbi", "secret service"],
	"government-agent":["cia", "fbi", "secret service"],
	"federal-agent":["cia", "fbi", "secret service"],
	"*secret-service":["cia", "fbi", "secret service"],
	"*cinemato":["cinematography"],
	"*filmmak":["cinematography", "movie business"],
	"classic-car":["classic car", "cars"],
	"classical-music":["classical music", "music", "musicians"],
	"*claustro":["claustrophobic"],
	"*clon":["clones", "cloning"],
	"*college":["college"],
	"*university":["college"],
	"campus":["college"],
	"*fraternity":["college"],
	"*colonial":["colonialism"],
	"*coming-of-age":["coming of age", "coming-of-age"],
	"*communis":["communism"],
	"*competit":["competition"],
	"*tournament":["competition"],
	"*contest":["competition"],
	"*computer":["computers", "technology"],
	"arcade-game":["computer game", "video game", "video games", "videogame"],
	"computer-game":["computer game", "video game", "video games", "videogame"],
	"*video-game":["computer game", "video game", "video games", "videogame"],
	"con-artist":["con artists", "con men"],
	"con-man":["con artists", "con men"],
	"con-woman":["con artists", "con men"],
	"*confront":["confrontational"],
	"*conspiracy":["conspiracy", "conspiracy theory"],
	"*controversial":["controversial"],
	"*cook":["cooking"],
	"*corrupt":["corruption"],
	"courtroom":["court", "courtroom", "courtroom drama"],
	"court":["court", "courtroom", "courtroom drama"],
	"courthouse":["court", "courtroom", "courtroom drama"],
	"court-trial":["court", "courtroom", "courtroom drama"],
	"courtroom-drama":["court", "courtroom", "courtroom drama"],
	"court-hearing":["court", "courtroom", "courtroom drama"],
	"supreme-court":["court", "courtroom", "courtroom drama"],
	"court-case":["court", "courtroom", "courtroom drama"],
	"courage":["courage"],
	"creativity":["creativity"],
	"creative-process":["creativity"],
	"*horror":["creepy", "scary", "horror", "eerie", "frightening"],
	"*creepy":["creepy", "scary", "horror", "eerie", "frightening"],
	"*spooky":["creepy", "scary", "horror", "eerie", "frightening"],
	"genre:'Horror'":["creepy", "scary", "horror", "eerie", "frightening"],
	"*crime":["crime", "organized crime"],
	"genre:'Crime'":["crime", "organized crime"],
	"*cross-dress":["cross dressing"],
	"crude-humor":["crude humor", "dark humor", "dark comedy"],
	"dark-humor":["crude humor", "dark humor", "dark comedy"],
	"*cuba":["cuba"],
	"country:'Cuba'":["cuba"],
	"cult-film":["cult film", "cult classic", "classic"],
	"cult-tv":["cult film", "cult classic", "classic"],
	"cult":["cult"],
	"culture-clash":["culture clash"],
	"culture-shock":["culture clash"],
	"cyberpunk":["cyberpunk"],
	"*cynic":["cynical"],
	"*coen":["coen bros", "coen brothers"],
	"crew:'Ethan Coen'":["coen bros", "coen brothers"],
	"crew:'Joel Coen'":["coen bros", "coen brothers"],

	#============================================ D =============================================
	"*danc":["dance", "dancing"],
	"dark":["dark"],
	"dark-fantasy":["dark fantasy"],
	"dark-hero":["dark hero"],
	"*dc-comic":["dc comics"],
	"companies:'DC Comics'":["dc comics"],
	"*deadpan":["deadpan"],
	"dry-humor":["deadpan"],
	"dry-humour":["deadpan"],
	"*death":["death"],
	"*dead":["death"],
	"*suicide":["death"],
	"*execution":["death penalty", "death"],
	"death-penalty":["death penalty"],
	"*death-row":["death penalty", "death"],
	"*demon":["demons", "devil"],
	"*devil":["demons", "devil"],
	"*satan":["demons", "devil"],
	"*johnny-depp":["depp & burton"],
	"*tim-burton":["depp & burton"],
	"crew:'Johnny Depp'":["depp & burton"],
	"crew:'Tim Burton'":["depp & burton"],
	"sadness":["depressing", "sad"],
	"sad-ending":["depressing", "sad"],
	"*unhappy":["depressing", "sad"],
	"*depress":["depression", "depressing", "sad"],
	"melancholy":["melancholic", "melancholy", "depressing", "sad"],
	"*desert":["desert"],
	"*destiny":["destiny"],
	"fate":["destiny"],
	"*detective":["detective", "investigation", "private detective", "police investigation"],
	"*investigat":["detective", "investigation", "private detective", "police investigation"],
	"dialogue":["dialogue"],
	"*dialogue-driven":["dialogue driven", "dialogue"],
	"*dinosaur":["dinosaurs"],
	"directorial-debut":["directorial debut"],
	"*disability":["disability"],
	"*cripple":["disability"],
	"*handicap":["disability"],
	"*paralys":["disability"],
	"*disney":["disney"],
	"companies:/Disney/":["disney"],
	"*divorce":["divorce"],
	"doctor":["doctors", "hospital"],
	"medical-doctor":["doctors", "hospital"],
	"*medical":["doctors", "hospital"],
	"*hospital":["doctors", "hospital"],
	"genre:'Documentary'":["documentary"],
	"*dog":["dog", "dogs", "animal", "animal movie"],
	"*dolphin":["dolphins", "animal", "animal movie"],
	"*seuss":["dr. seuss"],
	"*dragon":["dragon", "dragons"],
	"genres:'Drama'":["drama"],
	"*dream":["dreams"],
	"dysfunctional-family":["dysfunctional family"],
	"dysfunctional-marriage":["dysfunctional family"],
	"*dystopia":["dystopic future", "distopia", "dystopia"],

	#============================================ E =============================================
	"*east-german":["east germany"],
	"*ecolog":["ecology"],
	"educational":["educational"],
	"educational-film":["educational"],
	"special-effects":["effects", "special effects"],
	"visual-effects":["effects", "special effects"],
	"digital-effects":["effects", "special effects"],
	"*egypt":["egypt"],
	"country:'Egypt'":["egypt"],
	"cast:'Emma Watson'":["emma watson"],
	"*england":["england"],
	"country:'England'":["england"],
	"*ennio-morricone":["ennio morricone"],
	"crew:'Ennio Morricone'":["ennio morricone"],
	"*nature":["environment", "environmental", "nature"],
	"*environment":["environment", "environmental", "nature"],
	"*wilderness":["environment", "environmental", "nature"],
	"landscape":["environment", "environmental", "nature"],
	"epic":["epic"],
	"epic-battle":["epic"],
	"ethnic-conflict":["ethnic conflict"],
	"evolution":["evolution"],
	"*explosion":["explosions"],

	#============================================ F =============================================
	"ice-skating":["figure skating"],
	"figure-skating":["figure skating"],
	"*fight":["fight scenes", "fighting", "action", "action packed"],
	"*battle":["fight scenes", "fighting", "action"],
	"fight-the-system":["fighting the system"],
	"*rebellion":["fighting the system"],
	"*protest":["fighting the system"],
	"*fairy-tale":["fairy tale", "fairy tales"],
	"fake-documentary":["fake documentary"],
	"fictional-documentary":["fake documentary"],
	"genres:'Family'":["family", "family bonds"],
	"family-conflict":["family drama"],
	"family-crisis":["family drama"],
	"family-abandonment":["family drama"],
	"family-in-danger":["family drama"],
	"family-betrayal":["family drama"],
	"genres:{'$all':['Family','Drama']}":["family drama"],
	"genre:'Fantasy'":["fantasy"],
	"fantasy-world":["fantasy world"],
	"*farce":["farce"],
	"*fascis":["fascism"],
	"*dictator":["fascism"],
	"fashion":["fashion"],
	"fashion-model":["fashion"],
	"fashion-designer":["fashion"],
	"fashion-industry":["fashion"],
	"fast-paced":["fast paced"],
	"*father-daughter":["father daughter relationship"],
	"*father-son":["father son relationship", "father-son relationship"],
	"*finnish":["finnish"],
	"*finland":["finnish"],
	"country:'Finland'":["finnish"],
	"*firefly":["firefly"],
	"*first-contact":["first contact", "alien", "aliens", "alien invasion"],
	"fishing":["fish"],
	"fish":["fish"],
	"*flashback":["flashbacks"],
	"*food":["food"],
	"*football":["football"],
	"*forced":["forceful"],
	"*foreign":["foreign"],
	"*profanity":["foul language"],
	"curse-word":["foul language"],
	"strong-language":["foul language"],
	"vulgar-language":["foul language"],
	"fountain-of-youth":["fountain of youth"],
	"eternal-youth":["fountain of youth"],
	"*france":["france", "french"],
	"*french":["france", "french"],
	"country:'France'":["france", "french"],
	"*franchise":["franchise"],
	"*francis-ford-copolla":["francis ford copolla"],
	"*freedom":["freedom", "free speech"],
	"free-speech":["freedom", "free speech"],
	"*futur":["future", "futuristic"],

	#============================================ G =============================================
	"*gang":["gangster", "gangsters", "gangs", "mob"],
	"*mobster":["gangster", "gangsters", "gangs", "mob"],
	"the-mob":["gangster", "gangsters", "gangs", "mob"],
	"*mafia":["gangster", "gangsters", "gangs", "mafia", "italian", "mob"],
	"*yakuza":["gangster", "gangsters", "gangs", "japan", "japanese", "mob"],
	"*geek":["geek", "geeks", "nerds"],
	"*nerd":["geek", "geeks", "nerds"],
	"*dork":["geek", "geeks", "nerds"],
	"*otaku":["geek", "geeks", "nerds", "japan", "japanese"],
	"*genetic":["genetics"],
	"*genius":["genius", "intelligent"],
	"*intelligent-":["genius", "intelligent"],
	"whiz-kid":["genius", "intelligent"],
	"math-whiz":["genius", "intelligent"],
	"computer-whizz":["genius", "intelligent"],
	"*genocide":["genocide"],
	"*german":["german", "germany"],
	"country:'Germany'":["german", "germany"],
	"*giant-robot":["giant robots"],
	"*global-warming":["global warming"],
	"god":["god"],
	"goddess":["god"],
	"gods":["god"],
	"greek-god":["god"],
	"demi-god":["god"],
	"evil-god":["god"],
	"*palm-tree":["golden palm"],
	"*golf":["golf"],
	"good-versus-evil":["good versus evil"],
	"*goth":["goth", "gothic"],
	"*graphic-design":["graphic design", "art", "artist", "artistic"],
	"graphic-novel":["graphic novel"],
	"*terry-gilliam":["gilliam"],
	"cast:'Terry Gilliam'":["gilliam"],
	"crew:'Terry Gilliam'":["gilliam"],
	"*greed":["greed"],
	"*selfish":["greed"],
	"*grindhouse":["grindhouse"],
	"grit":["gritty"],
	"gritty":["gritty"],
	"gross-out-comedy":["gross-out"],
	"gross-out":["gross-out"],
	"gross-out-humor":["gross-out"],
	"*guilt":["guilt"],
	"*regret":["guilt"],
	"*gulf-war":["gulf war"],
	"*gun":["guns", "gunfight"],

	#============================================ H =============================================
	"*hacker":["hackers", "hacking"],
	"*hacking":["hackers", "hacking"],
	"*halloween":["halloween"],
	"*hallucinat":["hallucinatory"],
	"*video-camera":["handycam"],
	"sony-handycam":["handycam"],
	"gopro":["handycam"],
	"*go-pro":["handycam"],
	"webcam":["handycam"],
	"*hannibal":["hannibal lecter", "cannibalism"],
	"happy-end":["happy ending"],
	"happy-ending":["happy ending"],
	"*harry-potter":["harry potter"],
	"title:/Harry Potter/":["harry potter"],
	"*haunted-house":["haunted house"],
	"*hawaii":["hawaii"],
	"heartbreaking":["heartbreaking", "depressing", "sad"],
	"heartbreaker":["heartbreaking", "depressing", "sad"],
	"happy":["heartwarming", "feel good movie", "feel-good"],
	"feel-good":["heartwarming", "feel good movie", "feel-good"],
	"heart-warming":["heartwarming", "feel good movie", "feel-good"],
	"*heroine":["heroine"],
	"high-fantasy":["high fantasy"],
	"*high-school":["high school"],
	"*hip-hop":["hip hop"],
	"genres:'History'":["historical", "history"],
	"*hitchcock":["hitchcock"],
	"crew:'Alfred Hitchcock'":["hitchcock"],
	"*holiday":["holiday"],
	"*vacation":["holiday"],
	"*hollywood":["hollywood", "california", "los angeles"],
	"*homeless":["homeless", "poverty"],
	"*homophobia":["homophobia"],
	"*honest":["honest"],
	"*hong-kong":["hong kong", "china"],
	"*horse":["horses", "animal", "animal movie"],
	"*stallion":["horses", "animal", "animal movie"],
	"*hotel":["hotel"],
	"*motel":["hotel"],
	"*hostel":["hotel"],
	"bed-and-breakfast":["hotel"],
	"*humanity":["humanity"],
	"human-race":["humanity"],
	"hunting":["hunting"],
	"hunter":["hunting"],

	#============================================ I =============================================
	"*idealis":["idealism"],
	"*identity":["identity"],
	"imaginary-friend":["imaginary friend"],
	"*imagina":["imagination"],
	"*immigra":["immigrants"],
	"*immortal":["immortality"],
	"*incest":["incest"],
	"*independent-film":["independent film", "indie"],
	"independent-short":["independent film", "indie"],
	"independent-horror":["independent film", "indie"],
	"independent-director":["independent film", "indie"],
	"*indie":["indie"],
	"independent-production":["indie"],
	"independent-media":["indie"],
	"independent-video-game":["indie"],
	"independent-music":["indie", "music", "musicians"],
	"independent-television":["indie"],
	"*indiana-jones":["indiana jones"],
	"title:/Indiana Jones/":["indiana jones"],
	"american-indian":["indians", "native americans"],
	"indians":["indians", "native americans"],
	"innocence-lost":["innocence lost"],
	"loss-of-innocence":["innocence lost"],
	"corruption-of-innocence":["innocence lost"],
	"*insan":["insanity"],
	"*inspiration":["inspirational", "inspiring"],
	"*internet":["internet"],
	"*online":["internet"],
	"*website":["internet"],
	"*web-":["internet"],
	"interracial-relationship":["interracial romance"],
	"interracial-romance":["interracial romance"],
	"interracial-sex":["interracial romance"],
	"interracial-couple":["interracial romance"],
	"*intimate":["intimate"],
	"*iran":["iran"],
	"country:'Iran'":["iran"],
	"*iraq":["iraq"],
	"country:'Iraq'":["iraq"],
	"*iraq-war":["iraq war"],
	"*ireland":["ireland", "irish"],
	"*irish":["ireland", "irish"],
	"country:'Ireland'":["ireland", "irish"],
	"*irish-accent":["irish accent"],
	"*ironic":["ironic"],
	"*irony":["ironic"],
	"*islam":["islam"],
	"island":["island"],
	"tropical-island":["island"],
	"mysterious-island":["island"],
	"desert-island":["island"],
	"remote-island":["island"],
	"*israel":["israel"],
	"country:'Israel'":["israel"],
	"*italy":["italy", "italian"],
	"*italian":["italy", "italian"],
	"country:'Italy'":["italy", "italian"],

	#============================================ J =============================================
	"*james-bond":["james bond", "007", "007 (series)"],
	"title:/James Bond/":["james bond", "007", "007 (series)"],
	"*jane-austen":["jane austen"],
	"*japan":["japan", "japanese"],
	"country:'Japan'":["japan", "japanese"],
	"*jazz":["jazz"],
	"*jesus":["jesus", "christian", "christianity", "biblical"],
	"judaism":["jewish", "jews", "judaism"],
	"rabbi":["jewish", "jews", "judaism"],
	"*mitzvah":["jewish", "jews", "judaism"],
	"*jewish":["jewish", "jews", "judaism"],
	"*journalis":["journalism"],
	"*reporter":["journalism"],
	"*jungle":["jungle"],
	"*rain-forest":["jungle"],
	"*rainforest":["jungle"],
	"justice":["justice"],
	"*-justice":["justice"],

	#============================================ K =============================================
	"*kidnap":["kidnapping", "hostage"],
	"*hostage":["kidnapping", "hostage"],
	"family-relationship":["kids and family", "family", "family bonds"],
	"*king-arthur":["king arthur"],
	"*excalibur":["king arthur"],
	"*kung-":["kung fu", "fight scenes", "fighting", "action", "action packed", "martial arts"],
	"*karate":["kung fu", "fight scenes", "fighting", "action", "action packed", "martial arts"],
	"*martial-":["kung fu", "fight scenes", "fighting", "action", "action packed", "martial arts"],
	"*kurosawa":["kurosawa", "japan", "japanese"],
	"*stanley-kubrick":["kubrick"],
	"crew:'Stanley Kubrick'":["kubrick"],

	#============================================ L =============================================
	"*vegas":["las vegas"],
	"*latin-america":["latin america"],
	"*lawyer":["lawyer", "lawyers"],
	"*lifestyle":["life"],
	"*-life":["life"],
	"*life-of":["life"],
	"life-choices":["life"],
	"life-coach":["life"],
	"*life-and-death":["life & death"],
	"meaning-of-life":["life philosophy", "existentialism"],
	"*existential":["life philosophy", "existentialism"],
	"*lion":["lions", "animal", "animal movie"],
	"*literary":["literature"],
	"*literature":["literature"],
	"cast:'Liv Tyler'":["liv tyler"],
	"*london":["london", "france", "french"],
	"*lonel":["loneliness"],
	"*los-angeles":["los angeles", "california"],
	"*love-triangle":["love triangles"],
	"*romantic-triangle":["love triangles"],
	"*low-budget":["low budget"],
	"*no-budget":["low budget"],
	"*micro-budget":["low budget"],
	"*tight-budget":["low budget"],
	"*david-lynch":["lynch"],
	"crew:'David Lynch'":["lynch"],
	"*lyric":["lyrical", "music", "musicians"],

	#============================================ M =============================================
	"macabre":["macabre"],
	"mad-scientist":["mad scientist"],
	"evil-scientist":["mad scientist"],
	"made-for-cable-tv":["made for tv", "television"],
	"made-for-tv-movie":["made for tv", "television"],
	"tv:1":["made for tv", "television"],
	"*magic":["magic"],
	"magical-realism":["magic realism"],
	"mystical-realism":["magic realism"],
	"*man-versus-machine":["man versus machine"],
	"*man-versus-robot":["man versus machine"],
	"*man-versus-computer":["man versus machine"],
	"*man-versus-cyborg":["man versus machine"],
	"*manipulat":["manipulation"],
	"*marri":["marriage"],
	"mars":["mars"],
	"mars-the-planet":["mars"],
	"*marvel":["marvel"],
	"companies:/Marvel/":["marvel"],
	"*marx-brothers":["marx brothers"],
	"*groucho-marx":["marx brothers"],
	"*harpo-marx":["marx brothers"],
	"*chico-marx":["marx brothers"],
	"cast:'Groucho Marx'":["marx brothers"],
	"cast:'Harpo Marx'":["marx brothers"],
	"cast:'Chico Marx'":["marx brothers"],
	"cast:'Zeppo Marx'":["marx brothers"],
	"*math":["math", "mathematics"],
	"maze":["maze"],
	"maze-game":["maze"],
	"maze-chase":["maze"],
	"hedge-maze":["maze"],
	"corn-maze":["maze"],
	"garden-maze":["maze"],
	"*medieval":["medieval"],
	"*meditati":["meditative"],
	"zen":["meditative"],
	"*memory":["memory"],
	"*mental-institution":["mental hospital", "mental illness"],
	"*mental-hospital":["mental hospital", "mental illness"],
	"*mental-patient":["mental hospital", "mental illness"],
	"*mental-illness":["mental illness"],
	"*mental-retardation":["mental illness"],
	"*mental-disorder":["mental illness"],
	"*mentor":["mentor"],
	"*metaphysic":["metaphysics"],
	"*mexic":["mexico"],
	"country:'Mexico'":["mexico"],
	"*middle-east":["middle east"],
	"midlife-crisis":["midlife crisis"],
	"mid-life-crisis":["midlife crisis"],
	"*mining":["mining"],
	"*miner":["mining"],
	"*minnesota":["minnesota"],
	"*missionary":["mission from god"],
	"mistaken-identity":["mistaken identity"],
	"*ghibli":["studio ghibli","miyazaki","anime","japan","japanese"],
	"companies:'Studio Ghibli'":["studio ghibli","miyazaki","anime","japan","japanese"],
	"crew:'Hayao Miyazaki'":["studio ghibli","miyazaki","anime","japan","japanese"],
	"angry-mob":["mob"],
	"lynch-mob":["mob"],
	"flash-mob":["mob"],
	"mockumentary":["mockumentary"],
	"fake-documentary":["mockumentary"],
	"mock-documentary":["mockumentary"],
	"spoof-documentary":["mockumentary"],
	"fictional-documentary":["mockumentary"],
	"science-fantasy":["modern fantasy"],
	"urban-fantasy":["modern fantasy"],
	"modern-fairy-tale":["modern fantasy"],
	"*money":["money"],
	"*monetary":["money"],
	"*cash":["money"],
	"*monkey":["monkey", "animal", "animal movie"],
	"*chimp":["monkey", "animal", "animal movie"],
	"*gorilla":["monkey", "animal", "animal movie"],
	"ape":["monkey", "animal", "animal movie"],
	"*monster":["monster", "monsters"],
	"*monty-python":["monty python"],
	"title:/Monty Python/":["monty python"],
	"mood-swing":["moody"],
	"bi-polar":["moody"],
	"bipolar-disorder":["moody"],
	"*moon":["moon"],
	"moral-dilemma":["moral ambiguity", "morality"],
	"moral-ambiguity":["moral ambiguity", "morality"],
	"moral-choice":["moral ambiguity", "morality"],
	"*moral":["morality"],
	"*mother-daughter":["mother daughter relationship"],
	"*mother-son":["mother-son relationship"],
	"*motorcycle":["motorcycle"],
	"*mountain-climb":["mountain climbing"],
	"*movie-studio":["movie business"],
	"*movie-director":["movie business"],
	"*movie-producer":["movie business"],
	"moving":["moving"],
	"moving-in":["moving"],
	"moving-out":["moving"],
	"moving-van":["moving"],
	"*mozart":["mozart"],
	"*mtv":["mtv"],
	"$and:[{'companies':/MTV/},{'companies':{'$not':/Magyar Televízió Müvelödési Föszerkesztöség/}},{'companies':{'$not':/Mainosteleviso/}}]":["mtv"],
	"multiple-storyline":["multiple storylines"],
	"multi-plot":["multiple storylines"],
	"*mummy":["mummy"],
	"*muppet":["muppets", "puppets"],
	"title:/Muppet/":["muppets", "puppets"],
	"*murder":["murder", "death"],
	"*killer":["murder", "death"],
	"murder-investigation":["murder mystery"],
	"murder-mystery":["murder mystery"],
	"genres:'Music'":["music", "musicians"],
	"genres:'Musical'":["musical"],
	"*music-industry":["music business", "music", "musicians"],
	"*music-business":["music business", "music", "musicians"],
	"record-producer":["music business", "music", "musicians"],
	"record-company":["music business", "music", "musicians"],
	"record-executive":["music business", "music", "musicians"],
	"record-label":["music business", "music", "musicians"],
	"record-contract":["music business", "music", "musicians"],
	"*mutant":["mutants"],
	"genres:'Mystery'":["mystery"],
	"*myth":["mythology"],
	"*folktale":["mythology"],
	"*folk-tale":["mythology"],

	#============================================ N =============================================
	"voice-over-narration":["narrated"],
	"narration":["narrated"],
	"narrator":["narrated"],
	"*narrated":["narrated"],
	"nasa":["nasa", "space program", "space", "space travel"],
	"reference-to-nasa":["nasa"],
	"natural-disaster":["natural disaster", "catastrophe", "disaster"],
	"*earthquake":["natural disaster", "catastrophe", "disaster"],
	"*tornado":["natural disaster", "catastrophe", "disaster"],
	"*tsunami":["natural disaster", "catastrophe", "disaster"],
	"meteor-impact":["natural disaster", "catastrophe", "disaster"],
	"forest-fire":["natural disaster", "catastrophe", "disaster"],
	"crew:'Niel Gaiman'":["neil gaiman"],
	"*neo-nazi":["neo-nazis", "nazi", "nazis"],
	"neo-noir":["neo-noir"],
	"tech-noir":["neo-noir"],
	"future-noir":["neo-noir"],
	"*new-jersey":["new jersey"],
	"*new-orleans":["new orleans"],
	"*new york":["new york", "new york city"],
	"big-apple":["new york", "new york city"],
	"*times-square":["new york", "new york city"],
	"*new-zealand":["new zealand"],
	"country:'New Zealand'":["new zealand"],
	"*ninja":["ninja"],
	"no-dialogue":["no dialogue"],
	"*nocturnal":["nocturnal"],
	"genres:'Film-Noir'":["noir", "film noir"],
	"genres:{'$all':['Thriller','Film-Noir']}":["noir thriller"],
	"*non-linear":["non-linear", "nonlinear"],
	"*nonlinear":["non-linear", "nonlinear"],
	"nostalgia":["nostalgia", "nostalgic"],
	"nostalgic":["nostalgia", "nostalgic"],
	"*nuclear":["nuclear", "nuclear bomb", "nuclear war"],
	"*nudity":["nudity"],
	"*nude":["nudity"],
	"*naked":["nudity"],
	"brief-male-full-frontal-nudity":["nudity (full frontal - brief)", "male nudity"],
	"brief-female-full-frontal-nudity":["nudity (full frontal - brief)"],
	"male-full-frontal-nudity":["nudity (full frontal)", "male nudity"],
	"female-full-frontal-nudity":["nudity (full frontal)"],
	"full-frontal-male-nudity":["nudity (full frontal)", "male nudity"],
	"full-frontal-female-nudity":["nudity (full frontal)"],
	"*rear-nudity":["nudity (rear)"],
	"*back-nudity":["nudity (rear)"],
	"brief-topless-female-nudity":["nudity (topless - brief)"],
	"topless-female-nudity":["nudity (topless)"],
	"*-male-nudity":["male nudity"],
	"*nude-male":["male nudity"],

	#============================================ O =============================================
	"*obsess":["obsession"],
	"*ocean":["ocean"],
	"sea":["ocean"],
	"oil":["oil"],
	"*oil-":["oil"],
	"*olympic":["olympics"],
	"*opera":["opera"],
	"*orphan":["orphans"],

	#============================================ P =============================================
	"*palestine":["palestine"],
	"country:'Palestine'":["palestine"],
	"parallel-universe":["parallel universe", "alternate reality", "alternate universe"],
	"parallel-world":["parallel universe", "alternate reality", "alternate universe"],
	"parallel-worlds":["parallel universe", "alternate reality", "alternate universe"],
	"parallel-dimension":["parallel universe", "alternate reality", "alternate universe"],
	"*dimension":["alternate reality", "alternate universe"],
	"*paranoi":["paranoia", "paranoid"],
	"*parenthood":["parenthood"],
	"*parenting":["parenthood"],
	"*paris":["paris", "france", "french"],
	"*parody":["parody", "spoof", "satire", "satirical"],
	"*spoof":["parody", "spoof", "satire", "satirical"],
	"*satir":["parody", "spoof", "satire", "satirical"],
	"*passionate":["passionate"],
	"*penguin":["penguins", "animal", "animal movie"],
	"period-piece":["period piece"],
	"period-film":["period piece"],
	"*peter-pan":["peter pan"],
	"title:/Peter Pan/":["peter pan"],
	"*philosoph":["philosophical", "philosophy"],
	"*photograph":["photographer", "photography"],
	"pig":["pigs", "animal", "animal movie"],
	"cartoon-pig":["pigs", "animal", "animal movie"],
	"*pirate":["pirates", "swashbuckler"],
	"swashbuckler":["pirates", "swashbuckler"],
	"companies:'Pixar Animation Studios'":["pixar", "pixar animation"],
	"*plot-twist":["plot twist", "twist"],
	"*poet":["poetry"],
	"*poker":["poker", "gambling"],
	"*poland":["poland"],
	"polish":["poland"],
	"polish-history":["poland"],
	"country:'Poland'":["poland"],
	"*police":["police"],
	"*-cop":["police"],
	"police-brutality":["police corruption"],
	"police-corruption":["police corruption"],
	"corrupt-cop":["police corruption"],
	"corrupt-police":["police corruption"],
	"crooked-cop":["police corruption"],
	"*politic":["political", "politics"],
	"government":["political", "politics"],
	"political-corruption":["political corruption"],
	"corrupt-politician":["political corruption"],
	"crooked-politician":["political corruption"],
	"government-corruption":["political corruption"],
	"*porn":["pornography", "sex", "sexy", "erotic", "sexual"],
	"*poverty":["poverty"],
	"poor":["poverty"],
	"*pregnan":["pregnancy"],
	"*prejudice":["prejudice"],
	"*discrimination":["prejudice"],
	"*bigotry":["prejudice"],
	"*prequel":["prequel"],
	"president":["president"],
	"u.s.-president":["president"],
	"american-president":["president"],
	"presidential-campaign":["president"],
	"pretentiousness":["pretentious"],
	"*prison":["prison"],
	"island-prison":["island", "prison"],
	"*prison-break":["prison escape"],
	"escaped-prisoner":["prison escape"],
	"escape-from-prison":["prison escape"],
	"*prison-escape":["prison escape"],
	"*product-placement":["product placement"],
	"prohibition":["prohibition"],
	"prohibition-era":["prohibition"],
	"*propaganda":["propaganda"],
	"*prostitut":["prostitution"],
	"psychadelic-image":["psychedelic", "hallucinatory"],
	"*psychiatr":["psychiatry", "psychiatrist"],
	"*psycholog":["psychological", "psychology"],
	"*pulp-fiction":["pulp"],
	"pulp-adventure":["pulp"],
	"pulp-novel":["pulp"],
	"pulp":["pulp"],
	"*punk":["punk"],
	"*puppet":["puppets"],

	#============================================ Q =============================================
	"*queer":["queer", "gay", "lesbian", "gay character", "homosexuality", "glbt", "sexuality"],
	"*gay":["queer", "gay", "lesbian", "gay character", "homosexuality", "glbt", "sexuality"],
	"*homosexual":["queer", "gay", "lesbian", "gay character", "homosexuality", "glbt", "sexuality"],
	"*lesbian":["queer", "gay", "lesbian", "gay character", "homosexuality", "glbt", "sexuality"],
	"*bisexual":["glbt", "sexuality"],
	"*transsexual":["glbt", "sexuality", "transgender"],
	"*transgender":["glbt", "sexuality", "transgender"],
	"*quirk":["quirky", "eccentricity"],

	#============================================ R =============================================
	"*rabbit":["rabbits", "animal", "animal movie"],
	"*bunny":["rabbits", "animal", "animal movie"],
	"hare":["rabbits", "animal", "animal movie"],
	"race":["race", "racing"],
	"race-track":["race", "racing"],
	"racetrack":["race", "racing"],
	"*racing":["race", "racing"],
	"*racism":["racism", "prejudice", "race issues"],
	"race-riot":["racism", "prejudice", "race issues"],
	"race-war":["racism", "prejudice", "race issues"],
	"racial-prejudice":["racism", "prejudice", "race issues"],
	"racial-issues":["racism", "prejudice", "race issues"],
	"racial-violence":["racism", "prejudice", "race issues"],
	"racial-injustice":["racism", "prejudice", "race issues"],
	"racial-intolerance":["racism", "prejudice", "race issues"],
	"racial-hatred":["racism", "prejudice", "race issues"],
	"*radio":["radio"],
	"*rags-to-riches":["rags to riches"],
	"*rape":["rape"],
	"rat":["rats"],
	"lab-rat":["rats"],
	"giant-rat":["rats"],
	"pet-rat":["rats"],
	"cartoon-rat":["rats"],
	"realistic":["realistic"],
	"realism":["realistic"],
	"hyperrealism":["realistic"],
	"genres:'Reality-TV'":["reality tv"],
	"*rebellion":["rebellion"],
	"*redemption":["redemption"],
	"*relationship":["relationships"],
	"*religion":["religion"],
	"*remake":["remade", "remake"],
	"*remade":["remade", "remake"],
	"*revolution":["revolution"],
	"*rio-de-janeiro":["rio de janeiro", "brazil"],
	"road-movie":["road movie", "road trip", "travel"],
	"road-trip":["road movie", "road trip", "travel"],
	"road-comedy":["road movie", "road trip", "travel"],
	"*roald-dahl":["roald dahl"],
	"*robber":["robbery", "heist"],
	"*heist":["robbery", "heist"],
	"reference-to-robert-downey-jr.":["robert downey jr"],
	"cast:'Robert Downey Jr.'":["robert downey jr"],
	"*robert-ludlum":["robert ludlum"],
	"crew:'Robert Ludlum'":["robert ludlum"],
	"*rock-and-roll":["rock and roll", "music", "musicians"],
	"genres:'Romance'":["romance", "romantic", "love", "love story"],
	"genres:{'$all':['Romance','Comedy']}":["romantic comedy"],
	"rome-italy":["rome", "italy", "italian"],
	"acient-rome":["rome"],
	"roman":["rome"],
	"roman-empire":["rome"],
	"*runaway":["runaway"],
	"run-away":["runaway"],
	"*russia":["russia", "russian"],
	"country:'Russia'":["russia", "russian"],

	#============================================ S =============================================
	"*sacrific":["sacrifice"],
	"*samurai":["samurai"],
	"*san-francisco":["san francisco", "california"],
	"*sarcas":["sarcasm"],
	"*saturday-night-live":["saturday night live"],
	"title:/Saturday Night Live/":["saturday night live"],
	"title:/SNL/":["saturday night live"],
	"scenery":["scenic", "environment", "environmental", "nature"],
	"scenic":["scenic", "environment", "environmental", "nature"],
	"scenic-beauty":["scenic", "environment", "environmental", "nature"],
	"scenic-route":["scenic", "environment", "environmental", "nature"],
	"*schizophreni":["schizophrenia"],
	"*school":["school"],
	"genres:'Sci-Fi'":["sci fi", "sci-fi", "scifi", "science fiction"],
	"*scien":["science"],
	"*scotland":["scotland"],
	"*scottish":["scotland"],
	"country:'Scotland'":["scotland"],
	"*screwball":["screwball", "screwball comedy"],
	"*secret":["secrets"],
	"segregation":["segregation"],
	"racial-segregation":["segregation", "racism", "prejudice", "race issues"],
	"*self-discovery":["self discovery"],
	"*sentimental":["sentimental"],
	"*sequel":["sequel", "sequels"],
	"*serial-killer":["serial killer"],
	"*series":["series"],
	"*sex":["sex", "sexy", "erotic", "sexual"],
	"*sexy":["sexy", "erotic", "sexual"],
	"*sexuality":["sexuality"],
	"*sex-comedy":["sex comedy"],
	"*erotic-comedy":["sex comedy"],
	"*sex-abuse":["sexual abuse"],
	"*sexual-abuse":["sexual abuse"],
	"*sexual-violence":["sexualized violence"],
	"*shakespeare":["shakespeare"],
	"*shark":["shark", "animal", "animal movie"],
	"*shopping":["shopping"],
	"short-story":["short"],
	"independent-short":["short"],
	"short-term-memory-loss":["short-term memory loss", "amnesia", "memory loss"],
	"silent-film":["silent"],
	"silent-movie":["silent"],
	"silent":["silent"],
	"single-father":["single father"],
	"single-dad":["single father"],
	"*sister-sister":["sisters"],
	"*sisters":["sisters"],
	"*sister-in-law-sister-in-law":["sisters"],
	"*half-sister-half-sister":["sisters"],
	"sister-versus-sister":["sisters"],
	"*skinhead":["skinhead"],
	"slacker":["slackers"],
	"*slapstick":["slapstick"],
	"*slasher":["slasher"],
	"*slave":["slavery"],
	"*small-town":["small town"],
	"*small-village":["small town"],
	"*small-community":["small town"],
	"*snake":["snakes"],
	"cobra":["snakes"],
	"king-cobra":["snakes"],
	"python":["snakes"],
	"*soccer":["soccer"],
	"social-commentary":["social commentary"],
	"cast:'Sophia Copolla'":["sophia coppola"],
	"crew:'Sophia Copolla'":["sophia coppola"],
	"*south-africa":["south africa", "africa"],
	"*south-america":["south america"],
	"*southerner":["southern theme"],
	"southern":["southern theme"],
	"*space":["space"],
	"*space-travel":["space travel", "space program", "space"],
	"*space-flight":["space travel", "space program", "space"],
	"*space-exploration":["space travel", "space program", "space"],
	"*space-opera":["space opera"],
	"*spaghetti-western":["spaghetti western"],
	"*spain":["spain"],
	"country:'Spain'":["spain"],
	"*spanish":["spanish"],
	"spanish-civil-war":["spanish civil war"],
	"tv-special":["special", "television", "made for tv"],
	"television-special":["special", "television", "made for tv"],
	"christmas-special":["special"],
	"concert-special":["special", "music", "musicians"],
	"special-feature":["special"],
	"spelling-bee":["spelling bee"],
	"*spider":["spiders"],
	"*spielberg":["spielberg"],
	"crew:'Steven Spielberg'":["spielberg"],
	"*star-trek":["star trek"],
	"*spock":["star trek", "spock"],
	"title:/Star Trek/":["star trek", "spock"],
	"genres:'Sport'":["sports"],
	"*spy":["spy", "espionage", "spying", "spies"],
	"*stage-magician":["stage magic"],
	"*stand-up-comed":["stand-up comedy"],
	"stand-up":["stand-up comedy"],
	"stand-up-show":["stand-up comedy"],
	"stand-up-routine":["stand-up comedy"],
	"*star-wars":["star wars"],
	"title:/Star Wars/":["star wars"],
	"*steampunk":["steampunk"],
	"*steam-punk":["steampunk"],
	"*stereotype":["stereotypes"],
	"stoner-comedy":["stoner movie"],
	"*stop-motion":["stop motion", "stop-motion"],
	"story-telling":["storytelling"],
	"*storytell":["storytelling"],
	"*stripper":["strippers"],
	"*stupid":["stupidity"],
	"dumb":["stupidity"],
	"dumbness":["stupidity"],
	"*dumb-":["stupidity"],
	"*idiot":["stupidity"],
	"*submarine":["submarine"],
	"*suburbia":["suburbia"],
	"*suicide":["suicide", "suicide attempt"],
	"*superhero":["super hero", "super-hero", "superhero", "superheroes"],
	"*super-hero":["super hero", "super-hero", "superhero", "superheroes"],
	"*supernatural":["supernatural"],
	"*surf":["surfing"],
	"*surreal":["surreal", "surrealism", "dreamlike"],
	"*surveillance":["surveillance"],
	"*surviv":["survival"],
	"*suspense":["suspense", "suspenseful"],
	"*swedish":["swedish"],
	"*sweden":["swedish"],
	"country:'Sweden'":["swedish"],
	"switching-bodies":["switching places"],
	"switching-roles":["switching places"],
	"switching-sides":["switching places"],
	"swapping-lives":["switching places"],
	"trading-places":["switching places"],
	"*sword-fight":["sword fight", "sword fighting"],
	"*sword-duel":["sword fight", "sword fighting"],

	#============================================ T =============================================
	"*tarantino":["tarantino"],
	"crew:'Quentin Tarantino'":["tarantino"],
	"*teacher":["teacher"],
	"*professor":["teacher"],
	"*technology":["technology"],
	"*teen":["teen", "teenager", "teenagers", "teens"],
	"*teen-movie":["teen movie"],
	"*teen-comedy":["teen movie"],
	"*teleport":["teleportation"],
	"portal":["teleportation"],
	"terminal-illness":["terminal illness"],
	"terminal-disease":["terminal illness"],
	"terminal-cancer":["terminal illness"],
	"terminal-care":["terminal illness"],
	"fatal-illness":["terminal illness"],
	"fatal-disease":["terminal illness"],
	"*terroris":["terrorism"],
	"*texas":["texas"],
	"genres:'Thriller'":["thriller"],
	"time":["time"],
	"time-freeze":["time"],
	"*timeline":["time"],
	"*time-paradox":["time"],
	"*time-lord":["time"],
	"*space-time":["time"],
	"*time-dilation":["time"],
	"*time-displacement":["time"],
	"*time-distortion":["time"],
	"*time-manipulation":["time"],
	"*temporal":["time"],
	"*time-loop":["time loop", "time"],
	"*time-travel":["time travel", "time"],
	"*time-machine":["time travel", "time"],
	"time-portal":["time travel", "time"],
	"time-warp":["time travel", "time"],
	"time-reversal":["time travel", "time"],
	"lost-in-time":["time travel", "time"],
	"*tokyo":["tokyo", "japan", "japanese"],
	"*tolkien":["tolkien"],
	"*tom-clancy":["tom clancy"],
	"crew:'Tom Clancy'":["tom clancy"],
	"*toy":["toys"],
	"*tragedy":["tragedy", "depressing", "sad"],
	"*train":["train", "trains", "travel"],
	"*transform":["transformation"],
	"travel":["travel"],
	"travelogue":["travel"],
	"traveling":["travel"],
	"world-travel":["travel"],
	"traveler":["travel"],
	"*treasure":["treasure", "treasure hunt"],
	"*trilogy":["trilogy"],
	"truth":["true story", "factual"],
	"historical-truth":["true story", "factual"],
	"true-story":["true story", "factual"],
	"*truman-capote":["truman capote"],
	"crew:'Truman Capote'":["truman capote"],
	"*twist-ending":["twist", "twist ending", "plot twist", "surprise ending"],
	"twist-at-the-end":["twist", "twist ending", "plot twist", "surprise ending"],
	"*surprise-ending":["twist", "twist ending", "plot twist", "surprise ending"],

	#============================================ U =============================================
	"undercover-cop":["undercover cop"],
	"undercover-police":["undercover cop"],
	"undercover-policeman":["undercover cop"],
	"undercover-policewoman":["undercover cop"],
	"*underdog":["underdog"],
	"*underwater":["underwater"],
	"*united-nations":["united nations"],
	"american-history":["us history"],
	"*utopia":["utopia"],

	#============================================ V =============================================
	"virtual-reality":["virtual reality"],
	"virtual-set":["virtual reality"],
	"virtuality":["virtual reality"],
	"virtual-world":["virtual reality"],
	"virtual":["virtual reality"],
	"virtual-reality-game":["virtual reality", "computer game", "video game", "video games", "videogame"],
	"virtual-life":["virtual reality"],
	"*vampire":["vampire", "vampires"],
	"*dracula":["vampire", "vampires"],
	"vampire-human-love":["vampire human love"],
	"vengeance":["vengeance", "revenge"],
	"revenge":["vengeance", "revenge"],
	"vienna-austria":["vienna"],
	"vietnam":["vietnam"],
	"country:'Vietnam'":["vietnam"],
	"vietnamese":["vietnam"],
	"*vigilant":["vigilante", "vigilantism", "justice"],
	"*virus":["virus"],
	"infection":["virus"],
	"*plague":["virus"],
	"*epidemic":["virus"],
	"*pandemic":["virus"],
	"contagious-disease":["virus"],
	"*contagious":["virus"],
	"*virgin":["virginity"],
	"*voodoo":["voodoo"],
	"black-magic":["voodoo"],
	"*witchcraft":["voodoo"],
	"*curse":["voodoo"],
	"*voyeur":["voyeurism"],

	#============================================ W =============================================
	"genres:'War'":["war", "war movie", "wartime", "military"],
	"world-war-two":["wwii", "world war ii"],
	"world-war-one":["world war i"],
	"cold-war-era":["cold war"],
	"*civil-war":["civil war"],
	"cold-war":["cold war"],
	"*vietnam-war":["vietnam war"],
	"vietnam-veteran":["vietnam war"],
	"vietnam-vet":["vietnam war"],
	"vietnam-flashback":["vietnam war"],
	"vietnam-memorial":["vietnam war"],
	"vietnamese-soldier":["vietnam war"],
	"american-civil-war":["american civil war"],
	"weapon":["weapons"],
	"*wedding":["wedding"],
	"weed":["weed", "drugs", "marijuana"],
	"smoking-weed":["weed", "drugs", "marijuana"],
	"*marijuana":["weed", "drugs", "marijuana"],
	"*cocaine":["weed", "drugs", "marijuana"],
	"methamphetamine":["weed", "drugs", "marijuana"],
	"crystal-meth":["weed", "drugs", "marijuana"],
	"meth":["weed", "drugs", "marijuana"],
	"meth-lab":["weed", "drugs", "marijuana"],
	"heroin":["weed", "drugs", "marijuana"],
	"*heroin-":["weed", "drugs", "marijuana"],
	"*drug":["weed", "drugs", "marijuana"],
	"*werewolf":["werewolf", "werewolves"],
	"genres:'Western'":["western"],
	"*witch":["witch", "witches"],
	"*wizard":["wizards"],
	"*working-class":["working class"],
	"*workplace":["workplace", "office", "business"],
	"office":["workplace", "office", "business"],
	"*politic":["world politics", "political", "politics"],
	"*writer":["writers", "writing", "writer's life"],

	#============================================ Z =============================================
	"*zombie":["zombie", "zombies"]
}


# IMDB Keywords that should be ignored while processing the given wildcard filters.
# Values with a * in front should ignore all keywords that contain that value as a substring.
#
#	For example, in the dictionary above we have:
#		"*dragon":["dragon", "dragons"]
#
#	While in the dictionary below we have:
#		"*dragon":["*dragonfly"]
#
#	Thus when pairing IMDB keywords with the substring "dragon" with the ["dragon"/"dragons"] tag, you
#   should skip all keywords that have the substring "dragonfly".

imdbIgnore = {
	"*abus":["substance-abuse", "alcohol-abuse", "drug-abuse", "prescription-drug-abuse", "abuse-of-power"],
	"*alien":["*illegal-alien"],
	"*autis":["flautist"],
	"*aviat":["aviator-sunglasses", "*la-traviata"],
	"*battle":["*custody-battle", "*rap-battle", "*legal-battle", "*court-battle"],
	"*berlin":["oberlin", "abberline", "*irving-berlin"],
	"*buddy":["*reference-to-buddy"],
	"*british":["*british-accent"],
	"*cash":["*johnny-cash"],
	"*chess":["*duchess"],
	"*cruise":["*cruise-missle", "*cruiser", "*tom-cruise"],
	"*-ship":["*space-ship", "*rocket-ship", "*shipment", "alien-ship"],
	"*christian":["hans-christian-andersen"],
	"*clon":["*cyclon", "insection-clone", "batman-clone", "mortal-combat-clone", "clonskeagh-dublin", "doom-clone", "leisure-suit-larry-clone", "tex-murphy-clone", "reference-to-saint-brendan-the-navigator-of-clonfert"],
	"*computer":["*computer-animat"],
	"*cook":["*cookie"],
	"*creepy":["creepy-crawlie"],
	"*cuba":["*scuba", "*incubat"],
	"*curse":["curse-word"],
	"*desert":["*desertion", "*deserted", "*desert-island", "*desert-eagle"],
	"*demon":["*demonst", "*pandemon"],
	"*devil":["*vaudeville", "*tasmanian-devil"],
	"*depress":["economic-depression", "*great-depression", "*depression-era", "depression-of-1929", "*depressor"],
	"*dog":["*dog-tag", "*dogfight", "*dog-fight", "*underdog", "*doggystyle", "*hot-dog", "*dogme", "*dogma", "*prairie-dog"],
	"*dream":["dream-girl", "dream-woman", "dream-job", "dream-house", "dream-home", "*dreamcast", "*dreamy"],
	"*drug":["*drugstore"],
	"*dragon":["*dragonfly"],
	"*ecolog":["*gynecolo"],
	"*fight":["*firefight", "*fire-fight", "*fighter-jet", "*food-fight", "*fighter-pilot", "*dogfight", "*dog-fight", "*pillow-fight", "fight-the-system", "*bullfight", "*bull-fight", "*cockfight", "*cock-fight", "*snowball-fight"],
	"*french":["*french-kiss", "*french-accent"],
	"*foreign":["foreign-language-adaptation"],
	"*franchise":["*disenfranchis"],
	"*german":["*german-shepherd", "*german-accent"],
	"*guilt":["*not-guilty", "guilty-verdict", "guilty-pleasure"],
	"*hitman":["*whitman"],
	"*hacker":["*whacker", "*thacker"],
	"*hacking":["*whacking", "hacking-off-limbs"],
	"*hitchcock":["*mark-l.-hitchcock"],
	"*honest":["*dishonest"],
	"*hypno":["*rohypnol"],
	"*horror":["b-horror"],
	"*horse":["*seahorse"],
	"*intelligent-":["intelligent-design"],
	"*investigat":["*paranormal-investigat", "*ghost-investigat"],
	"*irish":["*irish-accent"],
	"*iran":["*piranha", "*miranda"],
	"*jazz":["jazz-the-character"],
	"*jewish":["jewish-stereotype", "jewish-slur"],
	"*killer":["*pain-killer", "*killer-whale"],
	"*lion":["*llion", "*dandelion", "*lionfish", "*pavilion", "*alion"],
	"*lonel":["*colonel"],
	"*manipulat":["*time-manipulation", "*genetic-manipulation", "*gene-manipulation", "*weather-manipulation", "*video-manipulation"],
	"*math":["*aftermath", "*aromatherap", "*namath", "*mathis", "*arimathea", "*mathmo"],
	"*memory":["*memory-card", "*memory-stick", "*memory-game"],
	"*mexic":["*new-mexic"],
	"*mentor":["*tormentor"],
	"*mining":["*examining"],
	"*miner":["*examiner", "*minerva", "deminer"],
	"*monkey":["*monkey-wrench", "*monkey-bar"],
	"*moral":["*morale"],
	"*moon":["*moonshine", "*honeymoon", "*mooning"],
	"*nature":["*human-nature", "*signature"],
	"*oil-":["*oil-lamp", "*oil-paint", "*soil-"],
	"*online":["*nonlinear"],
	"*opera":["*soap-opera", "*operat"],
	"*paris":["*paris-hilton", "*comparison", "paris-texas"],
	"*penguin":["*pittsburgh-penguins"],
	"*pirate":["*pittsburgh-pirates", "*pirated"],
	"*protest":["*protestant"],
	"*poker":["*fire-poker", "*fireplace-poker", "red-hot-poker"],
	"*punk":["*spunk"],
	"*rabbit":["*volkswagen-rabbit", "rabbit's-foot*"],
	"*rape":["*skyscrape", "*trapeze", "*grape", "*serape"],
	"*revolution":["*dance-dance-revolution"],
	"*russia":["prussia"],
	"*robot":["ostrobothnia-finland"],
	"*scien":["*conscien", "*scientolo"],
	"*scottish":["*scottish-accent"],
	"*secret":["*secretary"],
	"*sex":["*essex", "homosexual", "transsexual", "bisexual", "heterosexual", "*sexuality", "closeted-homosexual", "*sexual-orientation", "*sexis", "*sexy"],
	"*shark":["*loan-shark", "*card-shark"],
	"*space":["*cyberspace", "*myspace", "*crawlspace", "*crawl-space", "*parking-space", "*office-space", "*space-needle", "*spacey"],
	"*spanish":["*spanish-accent"],
	"*spider":["*spider-man", "*spiderman"],
	"*spy":["*raspy"],
	"*surf":["*surface", "*channel", "*crowd", "*couch"],
	"*swedish":["*swedish-accent"],
	"*teen":["*canteen", "*osteen", "*teenth"],
	"*temporal":["*temporal-lobe"],
	"*texas":["*texas-hold"],
	"*tokyo":["*little-tokyo"],
	"*toy":["*sex-toy", "*toyota", "*stoy"],
	"*train":["*trainer", "*trained", "*training", "*restrain"],
	"*witch":["*switch", "*twitch"],
	"*virgin":["*virginia", "*virgin-mary"]
}