# [Key]   IMDB Keyword
# [Value] List of related MovieLens tags

# To determine which movies should have the MovieLens tags appended:
# 		- Default query on the IMDB db would be {"keywords":"key"}
# 		- Keys with a * in front should query the IMDB database for {"keywords":/key/}
# 		- Keys containing a : character (ie "0:1") should query the IMDB database for {"0":1}
# 		- Keys can have both a * and :, in which case query the IMDB database for {"0":/1/}
#
# Also see imdbIgnore at the bottom of this file.

imdbKeywords =
{
	#============================================ A =============================================
	"*9-11":["9/11"],
	"companies:'Aardman Animations'":["aardman", "aardman studios", "computer animation", "claymation"],
	"*abortion":["abortion"],
	"*action":["action", "action packed"],
	"genre:'Action'":["action", "action packed"],
	"*adventure":["adventure"],
	"genre:'Adventure'":["adventure"],
	"*addiction":["addiction"],
	"drug-abuse":["addiction", "drug abuse", "drug addiction"],
	"prescription-drug-abuse":["addiction", "drug abuse", "drug addiction"],
	"substance-abuse":["addiction", "drug abuse", "drug addiction"],
	"*adolescen":["adolescence"],
	"*adopt":["adoption"],
	"*adulter":["adultery"],
	"cheating-wife":["adultery"],
	"cheating-husband":["adultery"],
	"africa":["africa"],
	"african":["africa"],
	"south-africa":["africa"],
	"north-africa":["africa"],
	"african-tribe":["africa"],
	"afterlife":["afterlife", "ghosts/afterlife"],
	"belief-in-the-afterlife":["afterlife", "ghosts/afterlife"],
	"ghost":["afterlife", "ghosts", "ghosts/afterlife"],
	"heaven":["afterlife"],
	"hell":["afterlife"],
	"aging":["aging"],
	"rapid-aging":["aging"],
	"aids":["aids"],
	"hiv-aids":["aids"],
	"airplane":["airplane", "aviation"],
	"airplane-crash":["airplane"],
	"airplane-accident":["airplane"],
	"plane-crash":["airplane"],
	"airplane-pilot":["airplane", "aviation"],
	"airplane-trip":["airplane"],
	"*airport":["airport"],
	"*aviat":["aviation"],
	"*alaska",["alaska"],
	"*alcatraz":["alcatraz", "prison"],
	"*alcoholic":["alcoholism", "addiction"],
	"alcoholism":["alcoholism", "addiction"],
	"alcohol-abuse":["alcoholism", "addiction"],
	"*alien":["alien", "aliens", "alien invasion"],
	"alone":["alone in the world", "isolation"],
	"last-man-on-earth":["alone in the world", "isolation"],
	"*stranded":["alone in the world", "isolation", "stranded"],
	"deserted-island":["alone in the world", "isolation", "stranded"],
	"solitary-confinement":["alone in the world", "isolation"],
	"*isolat":["alone in the world", "isolation"],
	"amnesia":["amnesia", "memory loss"],
	"memory-loss":["amnesia", "memory loss"],
	"loss-of-memory":["amnesia", "memory loss"],
	"*robot":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"*cyborg":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"*android":["android(s)/cyborg(s)", "androids", "cyborgs", "robot", "robots"],
	"animal":["animal", "animal movie"],
	"anthropomorphic-animal":["animal", "animal movie"],
	"talking-animal":["animal", "talking animals", "animal movie"],
	"human-animal-relationship":["animal", "animal movie"],
	"alternate-reality":["alternate reality", "alternate universe"],
	"alternative-reality":["alternate reality", "alternate universe"],
	"post-apocalypse":["apocalypse", "post apocalyptic", "post-apocalyptic"],
	"apocalypse":["post apocalyptic", "post-apocalyptic", "catastrophe", "disaster", "end of the world"],
	"*end-of-the-world":["post apocalyptic", "post-apocalyptic", "catastrophe", "disaster", "end of the world"],
	"zombie-apocalypse":["apocalypse", "post apocalyptic", "post-apocalyptic", "zombie", "zombies"],
	"genres:'Animation'":["animated", "animation"],
	"2d-animation":["animated", "animation", "cartoon"],
	"part-animation":["animated", "animation"],
	"stop-motion-animation":["animated", "animation"],
	"computer-animation":["animated", "animation", "computer animation"],
	"3d-animation":["animated", "animation", "computer animation", "cgi"],
	"animation-filmmaking":["animated", "animation"],
	"part-computer-animation":["animated", "animation", "computer animation", "cgi"],
	"clay-animation":["animated", "animation", "claymation"],
	"claymation":["animated", "animation", "claymation"],
	"cgi":["computer animation", "cgi"],
	"cgi-animation":["animated", "animation", "computer animation", "cgi"],
	"cgi-film":["computer animation", "cgi"],
	"*anime":["anime", "animated", "animation", "japan", "japanese"],
	"artificial-intelligence":["artificial intelligence"],
	"*arctic":["antarctica"],
	"anti-hero":["anti-hero"],
	"anti-heroine":["anti-hero"],
	"anti-semitism":["anti-semitism"],
	"*nazi":["anti-semitism"],
	"*world-war-two":["anti-semitism"],
	"*world-war-ii":["anti-semitism"],
	"*hitler":["anti-semitism"],
	"*anti-war":["anti-war"],
	"*archeolo":["archaeology"],
	"*assassin":["assassin", "assassins", "assassination"],
	"*astronaut":["astronauts"],
	"video-art":["art", "artist", "artistic", "artsy"],
	"performance-art":["art", "artist", "artistic", "artsy"],
	"modern-art":["art", "artist", "artistic", "artsy"],
	"abstract-art":["art", "artist", "artistic", "artsy"],
	"art-gallery":["art", "artist", "artistic", "artsy"],
	"art-museum":["art", "artist", "artistic", "artsy"],
	"art-film":["art", "artist", "artistic", "artsy", "art house"],
	"art-house":["art", "artist", "artistic", "artsy", "art house"],
	"art-exhibition":["art", "artist", "artistic", "artsy"],
	"art-dealer":["art", "artist", "artistic", "artsy"],
	"art-student":["art", "artist", "artistic", "artsy"],
	"art-class":["art", "artist", "artistic", "artsy"],
	"art-history":["art", "artist", "artistic", "artsy"],
	"art-school":["art", "artist", "artistic", "artsy"],
	"art-studio":["art", "artist", "artistic", "artsy"],
	"art-teacher":["art", "artist", "artistic", "artsy"],
	"art-collector":["art", "artist", "artistic", "artsy"],
	"art-critic":["art", "artist", "artistic", "artsy"],
	"art-show":["art", "artist", "artistic", "artsy"],
	"art-installation":["art", "artist", "artistic", "artsy"],
	"art-project":["art", "artist", "artistic", "artsy"],
	"artist":["art", "artist", "artistic", "artsy"],
	"painter":["art", "artist", "artistic", "artsy"],
	"painting":["art", "artist", "artistic", "artsy"],
	"sculptor":["art", "artist", "artistic", "artsy"],
	"*australia":["australian", "australia"],
	"country:'Australia'":["australia", "australian"],
	"*atheis":["atheism"],
	"*autis":["autism"],
	"":["almodovar"],
	"crew:'Pedro Almodóvar'":["almodovar"],
	"":["amy smart"],
	"cast:'Amy Smart'":["amy smart"],
	"":["arnold"],
	"cast:'Arnold Schwarzenegger'":["arnold"],

	#============================================ B =============================================
	"b-movie":["bad acting", "bad", "cheesy", "corny", "unintentionally funny", "so bad it's funny", "so bad it's good"],
	"b-horror":["bad acting", "bad", "cheesy", "corny", "unintentionally funny", "so bad it's funny", "so bad it's good"],
	"b-western":["bad acting", "bad", "cheesy", "corny", "unintentionally funny", "so bad it's funny", "so bad it's good"],
	"*baseball":["baseball"],
	"bank-robbery":["bank robbery", "robbery", "heist"],
	"bank-robber":["bank robbery", "robbery", "heist"],
	"*ballet":["ballet"],
	"based-on-novel":["based on a book", "adapted from:book", "based on book"],
	"based-on-book":["based on a book", "adapted from:book", "based on book"],
	"based-on-short-story":["based on a book", "adapted from:book", "based on book"],
	"based-on-story":["based on a book", "adapted from:book", "based on book"],
	"based-on-young-adult-novel":["based on a book", "adapted from:book", "based on book"],
	"based-on-poem":["based on a book", "adapted from:book", "based on book"],
	"based-on-fairy-tale":["fairy tale", "fairy tales", "based on a book", "adapted from:book", "based on book"],
	"based-on-folk-tale":["based on a book", "adapted from:book", "based on book"],
	"based-on-children's-book":["based on a book", "adapted from:book", "based on book", "kids", "children"],
	"based-on-comic-strip":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-comic-book":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-manga":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics", "japan", "japanese"],
	"based-on-comic":["adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics"],
	"based-on-graphic-novel":["graphic novel", "adapted from:comic", "based on a comic", "based on comic", "comic", "comic book", "comic book adaption", "comics", "based on a book", "adapted from:book", "based on book"],
	"based-on-game":["adapted from:game", "based on a video game", "computer game", "video game adaptation", "video game", "video games", "videogame"],
	"based-on-video-game":["adapted from:game", "based on a video game", "computer game", "video game adaptation", "video game", "video games", "videogame"],
	"based-on-stage-musical":["based on a play"],
	"based-on-play":["based on a play"],
	"based-on-opera":["based on a play"],
	"based-on-tv-series":["based on a tv show"],
	"based-on-tv-show":["based on a tv show"],
	"based-on-anime":["based on a tv show"],
	"based-on-cartoon":["based on a tv show"],
	"based-on-live-action-tv-series":["based on a tv show"],
	"based-on-tv-movie":["based on a tv show"],
	"based-on-television-series":["based on a tv show"],
	"based-on-british-tv-series":["based on a tv show"],
	"based-on-true-story":["based on a true story", "based on true story"],
	"based-on-real-events":["based on a true story", "based on true story"],
	"based-on-true-events":["based on a true story", "based on true story"],
	"based-on-supposedly-true-story":["based on a true story", "based on true story"],
	"based-on-fact":["based on a true story", "based on true story"],
	"based-on-autobiography":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"based-on-biography":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"autobiography":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"based-on-real-person":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"biographical":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"biopic":["based on a true story", "based on true story", "biographical", "biography", "biopic"],
	"genres:'Biography'":["based on a true story", "based on true story", "biographical", "biography", "biopic"]
	"*batman":["batman"],
	"*basketball":["basketball"],
	"*beatles":["beatles"],
	"beauty-contest":["beauty pageant", "fashion"],
	"beauty-pageant":["beauty pageant", "fashion"],
	"*pageant":["beauty pageant", "fashion"],
	"*miss-":["beauty pageant", "fashion"],
	"*fashion-show":["beauty pageant", "fashion"],
	"beer":["beer", "drinking"],
	"beer-drinking":["beer", "drinking"],
	"alcohol":["beer", "drinking", "wine"],
	"alcoholic-drink":["beer", "drinking", "wine"],
	"*berlin":["berlin"],
	"*betray":["betrayal"],
	"*bibl":["christian", "christianity", "biblical"],
	"*bird":["birds"],
	"*bizarre":["bizarre", "weird"],
	"blaxploitation":["blaxploitation"],
	"blindness":["blindness"],
	"blind":["blindness"],
	"blind-man":["blindness"],
	"blind-woman":["blindness"],
	"blind-boy":["blindness"],
	"blind-girl":["blindness"],
	"*blood":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"*violen":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"gore":["blood", "bloody", "gore", "goretastic", "gory", "violence", "violent", "gruesome"],
	"*bording-school":["boarding school"],
	"*boat":["boat"],
	"*cruise":["boat"],
	"*-ship":["boat"],
	"*bollywood":["bollywood", "india"],
	"country:'India'":["bollywood", "india"],
	"*bomb":["bombs"],
	"*bowling":["bowling"],
	"bowler":["bowling"],
	"*boston":["boston"],
	"*brazil":["brazil"],
	"country:'Brazil'":["brazil"],
	"*brainwash":["brainwashing"],
	"*hypno":["brainwashing"],
	"black-and-white-scene":["black and white"],
	"black-and-white":["black and white"],
	"some-scenes-in-black-and-white":["black and white"],
	"black-comedy":["black comedy"],
	"black-humor":["black comedy"],
	"boxing":["boxing"],
	"kickboxing":["boxing"],
	"boxing-match":["boxing"],
	"boxing-ring":["boxing"],
	"boxing-gloves":["boxing"],
	"boxing-gym":["boxing"],
	"boxing-champion":["boxing"],
	"boxing-glove":["boxing"],
	"boxing-trainer":["boxing"],
	"boxing-training":["boxing"],
	"british-comedy":["british comedy"],
	"british-humor":["british comedy"],
	"*british":["british"],
	"*bbc":["british"],
	"country:'UK'":["british"],
	"*broadway":["broadway"],
	"two-brothers":["brothers"],
	"three-brothers":["brothers"],
	"brother-vs-brother":["brothers"],
	"brother-brother-relationship":["brothers"],
	"twin-brother":["brothers"],
	"brotherhood":["brothers"],
	"brother-in-law-brother-in-law-relationship":["brothers"],
	"half-brother-half-brother-relationship":["brothers"],
	"*abus":["brutal", "brutality", "torture"],
	"*brutal":["brutal", "brutality", "torture"],
	"*tortur":["brutal", "brutality", "torture"],
	"*buddy":["buddy movie", "friendship"],
	"friendship":["buddy movie", "friendship"],
	"friend":["buddy movie", "friendship"],
	"best-friend":["buddy movie", "friendship"],
	"*bully":["bullying"],
	"*business":["business"],
	"*corporation":["business"],

	#============================================ C =============================================
	"*california":["california"],
	"campfire":["camp"],
	"camp":["camp"],
	"camping":["camp"],
	"campy":["campy"],
	"*canad":["canada"],
	"country:'Canada'":["canada"],
	"*cannibal":["cannibalism"],
	"*cancer":["cancer"],
	"*capitalis":["capitalism"],
	"*car-chase":["car chase", "cars", "chase"],
	"automobile-chase":["car chase", "cars", "chase"],
	"motorcycle-chase":["car chase", "cars", "chase"],
	"car-motorcycle-chase":["car chase", "cars", "chase"],
	"police-chase":["car chase", "cars", "chase"],
	"car":["cars"],
	"*race-car":["cars"],
	"*racecar":["cars"],
	"streetcar":["cars"],
	"street-racing":["cars"],
	"*nascar":["cars"],
	"*truck":["cars"],
	"*cartoon":["cartoon"],
	"*casino":["casino", "gambling"],
	"*gambl":["casino", "gambling"],
	"*christian":["christian", "christianity"],
	"*christmas",["christmas"],
	"*circus",["circus"],
	"*comedy",["comedy", "humor", "funny", "humorous", "hillarious", "hilarious"],
	"*humor",["comedy", "humor", "funny", "humorous", "hillarious", "hilarious"],
	"genre:'Comedy'":["comedy", "humor", "funny", "humorous", "hillarious", "hilarious"],
	"clown":["circus"],
	"*clown":["clowns"],
	"*catastroph":["catastrophe", "disaster"],
	"*disaster":["catastrophe", "disaster"],
	"*catholic":["catholicism"],
	"censorship":["censorship"],
	"censor":["censorship"],
	"film-censorship":["censorship"],
	"film-censor":["censorship"],
	"censorship-board":["censorship"],
	"media-censorship":["censorship"],
	"censored":["censorship"],
	"cerebral":["cerebral", "intellectual", "thought-provoking"],
	"intellectual":["cerebral", "intellectual", "thought-provoking"],
	"pseudo-intellectual":["cerebral", "intellectual", "thought-provoking"],
	"*chase":["chase"],
	"*cheerlead":["cheerleading"],
	"*chess":["chess"],
	"*chicago":["chicago"],
	"chick-flick":["chick flick", "girlie movie"],
	"*child-abuse":["child abuse"],
	"*childhood":["childhood", "children", "kids"],
	"children":["children", "kids"],
	"child":["children", "kids"],
	"child-protagonist":["children", "kids"],
	"*china":["china"],
	"country:'China'":["china"],
	"*chocolate":["chocolate"],
	"cia-agent":["cia", "fbi"],
	"ex-cia-agent":["cia", "fbi"],
	"female-cia-agent":["cia", "fbi"],
	"cia":["cia", "fbi"],
	"secret-agent":["cia", "fbi"],
	"fbi-agent":["cia", "fbi"],
	"agent":["cia", "fbi"],
	"undercover-agent":["cia", "fbi"],
	"government-agent":["cia", "fbi"],
	"federal-agent":["cia", "fbi"],
	"secret-service-agent":["cia", "fbi"],
	"*cinemato":["cinematography"],
	"*filmmak":["cinematography"],
	"classic-car":["classic car", "cars"],
	"classical-music":["classical music"],
	"*claustro":["claustrophobic"],
	"*clon":["clones", "cloning"],
	"*college":["college"],
	"*university":["college"],
	"campus":["college"],
	"*fraternity":["college"],
	"*colonial":["colonialism"],
	"*coming-of-age":["coming of age", "coming-of-age"],
	"*communis":["communism"],
	"*competit":["competition"],
	"*tournament":["competition"],
	"*contest":["competition"],
	"*computer":["computers"],
	"arcade-game":["computer game", "video game", "video games", "videogame"],
	"computer-game":["computer game", "video game", "video games", "videogame"],
	"*video-game":["computer game", "video game", "video games", "videogame"],
	"con-artist":["con artists", "con men"],
	"con-man":["con artists", "con men"],
	"con-woman":["con artists", "con men"],
	"*confront":["confrontational"],
	"*conspiracy":["conspiracy", "conspiracy theory"],
	"*controversial":["controversial"],
	"*cook":["cooking"],
	"*corrupt":["corruption"],
	"courtroom":["court", "courtroom", "courtroom drama"],
	"court":["court", "courtroom", "courtroom drama"],
	"courthouse":["court", "courtroom", "courtroom drama"],
	"court-trial":["court", "courtroom", "courtroom drama"],
	"courtroom-drama":["court", "courtroom", "courtroom drama"],
	"court-hearing":["court", "courtroom", "courtroom drama"],
	"supreme-court":["court", "courtroom", "courtroom drama"],
	"court-case":["court", "courtroom", "courtroom drama"],
	"courage":["courage"],
	"creativity":["creativity"],
	"creative-process":["creativity"],
	"*horror":["creepy", "scary", "horror", "eerie"],
	"*creepy":["creepy", "scary", "horror", "eerie"],
	"*spooky":["creepy", "scary", "horror", "eerie"],
	"genre:'Horror'":["creepy", "scary", "horror", "eerie"],
	"*crime":["crime"],
	"genre:'Crime'":["crime"],
	"*cross-dress":["cross dressing"],
	"crude-humor":["crude humor", "dark humor", "dark comedy"],
	"dark-humor":["crude humor", "dark humor", "dark comedy"],
	"*cuba":["cuba"],
	"country:'Cuba'":["cuba"],
	"cult-film":["cult film", "cult classic", "classic"],
	"cult-tv":["cult film", "cult classic", "classic"],
	"cult":["cult"],
	"culture-clash":["culture clash"],
	"culture-shock":["culture clash"],
	"cyberpunk":["cyberpunk"],
	"*cynic":["cynical"],
	"":["coen bros", "coen brothers"],
	"crew:'Ethan Coen'":["coen bros", "coen brothers"],
	"crew:'Joel Coen'":["coen bros", "coen brothers"],

	#============================================ D =============================================
	"*danc":["dance", "dancing"],
	"":["dark"],
	"":["dark fantasy"],
	"":["dark hero"],
	"*dc-comic":["dc comics"],
	"companies:'DC Comics'":["dc comics"],
	"":["deadpan"],
	"*death":["death"],
	"*dead":["death"],
	"*suicide":["death"],
	"*execution":["death penalty", "death"],
	"death-penalty":["death penalty"],
	"*death-row":["death penalty", "death"],
	"*demon":["demons", "devil"],
	"*devil":["demons", "devil"],
	"*satan":["demons", "devil"],
	"*johnny-depp":["depp & burton"],
	"*tim-burton":["depp & burton"],
	"crew:'Johnny Depp'":["depp & burton"],
	"crew:'Tim Burton'":["depp & burton"],
	"sadness":["depressing", "sad"],
	"sad-ending":["depressing", "sad"],
	"*unhappy":["depressing", "sad"],
	"*depress":["depression", "depressing", "sad"],
	"*desert":["desert"],
	"*destiny":["destiny"],
	"fate":["destiny"],
	"":["detective"],
	"dialogue":["dialogue"],
	"*dialogue-driven":["dialogue driven", "dialogue"],
	"*dinosaur":["dinosaurs"],
	"":["directorial debut"],
	"*disability":["disability"],
	"*cripple":["disability"],
	"*handicap":["disability"],
	"*paralys":["disability"],
	"*disney":["disney"],
	"*companies:Disney":["disney"],
	"":["disturbing"],
	"*divorce":["divorce"],
	"":["doctors"],
	"genre:'Documentary'":["documentary"],
	"*dog":["dog", "dogs", "animal", "animal movie"],
	"*dolphin":["dolphins", "animal", "animal movie"],
	"":["downbeat"],
	"*seuss":["dr. seuss"],
	"*dragon":["dragon", "dragons"],
	"genres:'Drama'":["drama"],
	"*dream":["dreams"],
	"dysfunctional-family":["dysfunctional family"],
	"dysfunctional-marriage":["dysfunctional family"],
	"*dystopia":["dystopic future", "distopia", "dystopia"],

	#============================================ E =============================================
	"":["earnest"],
	"*east-german":["east germany"],
	"":["eccentricity"],
	"":["ecology"],
	"educational":["educational"],
	"educational-film":["educational"],
	"":["effects"],
	"*egypt":["egypt"],
	"country:'Egypt'":["egypt"],
	"cast:'Emma Watson'":["emma watson"],
	"":["emotional"],
	"*england":["england"],
	"country:'England'":["england"],
	"":["enigmatic"],
	"":["ennio morricone"],
	"":["enormously long battle scene"],
	"":["ensemble cast"],
	"":["entertaining"],
	"":["entirely dialogue"],
	"":["environment", "environmental", "nature"],
	"":["epic"],
	"":["ethnic conflict"],
	"evolution":["evolution"],
	"":["exciting"],
	"":["existentialism"],
	"*explosion":["explosions"],

	#============================================ F =============================================
	"ice-skating":["figure skating"],
	"figure-skating":["figure skating"],
	"*fight":["fight scenes", "fighting", "action", "action packed"],
	"fight-the-system":["fighting the system"],
	"*rebellion":["fighting the system"],
	"*protest":["fighting the system"],
	"":["factual"],
	"*fairy-tale":["fairy tale", "fairy tales"],
	"":["fake documentary"],
	"genres:'Family'":["family"],
	"":["family bonds"],
	"":["family drama"],
	"genre:'Fantasy'":["fantasy"],
	"":["fantasy world"],
	"":["farce"],
	"":["fascism"],
	"fashion":["fashion"],
	"fashion-model":["fashion"],
	"fashion-designer":["fashion"],
	"fashion-industry":["fashion"],
	"":["fast paced"],
	"":["father daughter relationship"],
	"":["father son relationship"],
	"":["father-son relationship"],
	"*finnish":["finnish"],
	"*finland":["finnish"],
	"country:'Finland'":["finnish"],
	"":["firefly"],
	"":["first contact"],
	"":["fish"],
	"*flashback":["flashbacks"],
	"":["food"],
	"*football":["football"],
	"":["forceful"],
	"":["foreign"],
	"":["foul language"],
	"":["fountain of youth"],
	"*france":["france", "french"],
	"*french":["france", "french"],
	"country:'France'":["france", "french"],
	"":["franchise"],
	"":["francis ford copolla"],
	"":["free speech"],
	"":["free to download"],
	"":["freedom"],
	"":["frightening"],
	"":["fun"],
	"":["fun movie"],
	"":["future"],
	"":["futuristic"],

	#============================================ G =============================================
	"":["gambling"],
	"":["gangster", "gangsters", "gangs"],
	"":["geek", "geeks", "nerds"],
	"":["genetics"],
	"":["genius"],
	"":["genocide"],
	"":["george orwell"],
	"":["german", "germany"],
	"country:'Germany'":["german", "germany"],
	"":["giant robots"],
	"":["global warming"],
	"":["god"],
	"":["golden palm"],
	"":["golf"],
	"":["good versus evil"],
	"":["goofy"],
	"":["goth", "gothic"],
	"":["graphic design"],
	"graphic-novel":["graphic novel"],
	"":["gratuitous violence"],
	"":["gilliam"],
	"cast:'Terry Gilliam'":["gilliam"],
	"crew:'Terry Gilliam'":["gilliam"],
	"":["greed"],
	"":["grim"],
	"":["grindhouse"],
	"":["gritty"],
	"":["gross-out"],
	"":["gruesome"],
	"":["guilt"],
	"":["guilty pleasure"],
	"":["gulf war"],
	"":["gunfight"],
	"":["guns"],
	"":["gypsy accent"],

	#============================================ H =============================================
	"":["hackers", "hacking"],
	"":["halloween"],
	"":["hallucinatory"],
	"":["handycam"],
	"":["hannibal lecter"],
	"":["happy ending"],
	"":["hard to watch"],
	"*harry-potter":["harry potter"],
	"*title:Harry Potter":["harry potter"],
	"":["harsh"],
	"":["haunted house"],
	"":["hawaii"],
	"":["heartbreaking"],
	"":["heartwarming"],
	"":["heroine"],
	"":["heroine in tight suit"],
	"":["high fantasy"],
	"*high-school":["high school"],
	"":["hip hop"],
	"genres:'History'":["historical", "history"],
	"":["hit men", "hitman"],
	"":["hitchcock"],
	"crew:'Alfred Hitchcock'":["hitchcock"],
	"":["holiday"],
	"":["hollywood", "california", "los angeles"],
	"":["holocaust"],
	"*homeless":["homeless"],
	"":["homophobia"],
	"":["honest"],
	"":["hong kong", "china"],
	"":["horses"],
	"":["hospital"],
	"":["hostage"],
	"":["hotel"],
	"":["humanity"],
	"":["hunting"],

	#============================================ I =============================================
	"":["idealism"],
	"":["identity"],
	"":["idiotic"],
	"":["imaginary friend", "imagination"],
	"":["imagination"],
	"":["immigrants"],
	"":["immortality"],
	"":["incest"],
	"":["independent film", "indie"],
	"":["indiana jones"],
	"*title:Indiana Jones":["indiana jones"],
	"":["indians"],
	"":["infidelity"],
	"":["innocence lost"],
	"":["insanity"],
	"":["inspirational", "inspiring"],
	"":["intelligent"],
	"":["intelligent sci-fi"],
	"":["intense"],
	"":["interesting"],
	"":["internet"],
	"":["interracial romance"],
	"":["intimate"],
	"":["investigation"],
	"":["iran"],
	"country:'Iran'":["iran"],
	"":["iraq"],
	"country:'Iraq'":["iraq"],
	"":["iraq war"],
	"":["ireland", "irish"],
	"country:'Ireland'":["ireland", "irish"],
	"":["irish accent"],
	"":["ironic"],
	"":["irreverent"],
	"":["islam"],
	"":["island"],
	"":["israel"],
	"country:'Israel'":["israel"],
	"":["italy", "italian"],
	"country:'Italy'":["italy", "italian"],

	#============================================ J =============================================
	"*james-bond":["james bond", "007", "007 (series)"],
	"*title:James Bond":["james bond", "007", "007 (series)"],
	"*jane-austen":["jane austen"],
	"*japan":["japan", "japanese"],
	"country:'Japan'":["japan", "japanese"],
	"*jazz":["jazz"],
	"*jesus":["jesus", "christian", "christianity", "biblical"],
	"judaism":["jewish", "jews", "judaism"],
	"rabbi":["jewish", "jews", "judaism"],
	"*mitzvah":["jewish", "jews", "judaism"],
	"*jewish":["jewish", "jews", "judaism"],
	"*journalis":["journalism"],
	"*reporter":["journalism"],
	"*jungle":["jungle"],
	"*rain-forest":["jungle"],
	"*rainforest":["jungle"],
	"justice":["justice"],
	"*-justice":["justice"],

	#============================================ K =============================================
	"*kidnap":["kidnapping", "hostage"],
	"*hostage":["kidnapping", "hostage"],
	"family-relationship":["kids and family", "family", "family bonds"],
	"*king-arthur":["king arthur"],
	"*excalibur":["king arthur"],
	"*kung-":["kung fu", "fight scenes", "fighting", "action", "action packed"],
	"*karate":["kung fu", "fight scenes", "fighting", "action", "action packed"],
	"*martial-":["kung fu", "fight scenes", "fighting", "action", "action packed"],
	"*kurosawa":["kurosawa", "japan", "japanese"],
	"":["kubrick"],
	"crew:'Stanley Kubrick'":["kubrick"],

	#============================================ L =============================================
	"":["las vegas"],
	"":["latin america"],
	"":["lawyer", "lawyers"],
	"":["lesbian"],
	"":["life"],
	"":["life & death"],
	"":["life philosophy"],
	"":["light"],
	"":["lions"],
	"":["literary adaptation"],
	"":["literature"],
	"":["liv tyler"],
	"cast:'Liv Tyler'":["liv tyler"],
	"":["london", "france", "french"],
	"":["lone hero"],
	"":["loneliness"],
	"":["long"],
	"":["los angeles", "california"],
	"":["love triangles"],
	"":["low budget"],
	"":["lynch"],
	"crew:'David Lynch'":["lynch"],
	"":["lyrical"],

	#============================================ M =============================================
	"":["macabre"],
	"":["mad scientist"],
	"":["made for tv"],
	"":["mafia"],
	"":["magic"],
	"":["magic realism"],
	"":["male nudity"],
	"":["man versus machine"],
	"":["manipulation"],
	"":["marijuana"],
	"":["marriage"],
	"":["mars"],
	"":["martial arts"],
	"":["marvel"],
	"*companies:Marvel":["marvel"],
	"":["marx brothers"],
	"":["masterpiece"],
	"":["math", "mathematics"],
	"":["maze"],
	"":["medieval"],
	"":["meditative"],
	"":["melancholic", "melancholy"],
	"":["memory"],
	"":["mental hospital"],
	"":["mental illness"],
	"":["mentor"],
	"":["metaphysics"],
	"":["mexico"],
	"country:'Mexico'":["mexico"],
	"":["middle east"],
	"":["midlife crisis"],
	"":["military"],
	"":["mindfuck"],
	"":["mining"],
	"":["minnesota"],
	"":["mission from god"],
	"":["mistaken identity"],
	"companies:'Studio Ghibli'":["studio ghibli","miyazaki","anime","japan","japanese"],
	"crew:'Hayao Miyazaki'":["studio ghibli","miyazaki","anime","japan","japanese"],
	"":["mob"],
	"":["mockumentary"],
	"":["modern fantasy"],
	"":["money"],
	"":["monkey"],
	"":["monster", "monsters"],
	"":["monty python"],
	"*title:Monty Python":["monty python"],
	"":["moody"],
	"":["moon"],
	"":["moral ambiguity"],
	"":["morality"],
	"":["mother daughter relationship"],
	"":["mother-son relationship"],
	"":["motorcycle"],
	"":["mountain climbing"],
	"":["movie business"],
	"":["moving"],
	"":["mozart"],
	"":["mtv"],
	"":["multiple storylines"],
	"":["mummy"],
	"":["muppets"],
	"":["murder"],
	"":["murder mystery"],
	"genres:'Music'":["music", "musicians"],
	"genres:'Musical'":["musical"],
	"":["music business"],
	"":["mutants"],
	"genres:'Mystery'":["mystery"],
	"":["mythology"],

	#============================================ N =============================================
	"":["narrated"],
	"":["nasa"],
	"":["native americans"],
	"":["natural disaster"],
	"":["nazi", "nazis"],
	"":["neil gaiman"],
	"":["neo-nazis"],
	"":["neo-noir"],
	"":["new jersey"],
	"":["new orleans"],
	"":["new york", "new york city"],
	"":["new zealand"],
	"country:'New Zealand'":["new zealand"],
	"":["ninja"],
	"":["no dialogue"],
	"":["no plot"],
	"":["nocturnal"],
	"genres:'Film-Noir'":["noir", "film noir"],
	"genres:{$all:['Thriller','Film-Noir']}":["noir thriller"],
	"":["non-linear", "nonlinear"],
	"":["nostalgia", "nostalgic"],
	"":["nuclear", "nuclear bomb", "nuclear war"],
	"":["nudity"],
	"":["nudity (full frontal - brief)"],
	"":["nudity (full frontal - notable)"],
	"":["nudity (full frontal)"],
	"":["nudity (rear)"],
	"":["nudity (topless - brief)"],
	"":["nudity (topless - notable)"],
	"":["nudity (topless)"],

	#============================================ O =============================================
	"":["obsession"],
	"":["ocean"],
	"":["off-beat comedy"],
	"":["office"],
	"":["oil"],
	"":["olympics"],
	"":["ominous"],
	"":["opera"],
	"":["organized crime"],
	"":["orphans"],

	#============================================ P =============================================
	"":["palestine"],
	"country:'Palestine'":["palestine"],
	"":["parallel universe"],
	"":["paranoia", "paranoid"],
	"":["parenthood"],
	"":["paris", "france", "french"],
	"":["parody", "spoof", "satire", "satirical"],
	"":["passionate"],
	"":["penguins"],
	"":["perfect"],
	"":["period piece"],
	"":["peter pan"],
	"":["philip k. dick"],
	"":["philosophical", "philosophy"],
	"":["photographer", "photography"],
	"":["pigs", "animal", "animal movie"],
	"":["pirates", "swashbuckler"],
	"companies:'Pixar Animation Studios'":["pixar", "pixar animation"],
	"":["plot twist"],
	"":["poetry"],
	"":["poignant"],
	"":["pointless"],
	"":["poker"],
	"":["poland"],
	"country:'Poland'":["poland"],
	"":["police"],
	"":["police corruption"],
	"":["police investigation"],
	"":["political", "politics"],
	"":["political corruption"],
	"":["pornography"],
	"":["poverty"],
	"":["pregnancy"],
	"":["prejudice"],
	"":["prequel"],
	"":["president"],
	"":["pretentious"],
	"":["prison"],
	"":["prison escape"],
	"":["private detective"],
	"":["product placement"],
	"":["prohibition"],
	"":["propaganda"],
	"":["prostitution"],
	"":["psychedelic"],
	"":["psychiatrist"],
	"":["psychiatry"],
	"":["psychological", "psychology"],
	"":["pulp"],
	"":["punk"],
	"":["puppets"],

	#============================================ Q =============================================
	"*queer":["queer", "gay", "gay character", "homosexuality", "glbt"],
	"*gay":["queer", "gay", "gay character", "homosexuality", "glbt"],
	"*homosexual":["queer", "gay", "gay character", "homosexuality", "glbt"],
	"*quirk":["quirky"],

	#============================================ R =============================================
	"":["rabbits"],
	"":["race"],
	"":["race issues"],
	"":["racing"],
	"":["racism"],
	"":["radio"],
	"":["rags to riches"],
	"":["rape"],
	"":["rats"],
	"":["realistic"],
	"":["realistic action"],
	"genres:'Reality-TV'":["reality tv"],
	"":["rebellion"],
	"":["redemption"],
	"":["reflective"],
	"":["relationships"],
	"":["religion"],
	"":["remade"],
	"":["remake"],
	"":["revenge"],
	"":["revolution"],
	"":["ridiculous"],
	"":["rio de janeiro", "brazil"],
	"":["road movie", "road trip"],
	"":["roald dahl"],
	"":["robbery", "heist"],
	"":["robert downey jr"],
	"cast:'Robert Downey Jr.'":["robert downey jr"],
	"":["robert ludlum"],
	"crew:'Robert Ludlum'":["robert ludlum"],
	"":["rock and roll"],
	"genres:'Romance'":["romance", "romantic", "love", "love story"],
	"genres:{$all:['Romance','Comedy']}":["romantic comedy"],
	"":["rome"],
	"":["runaway"],
	"":["russia", "russian"],
	"country:'Russia'":["russia", "russian"],

	#============================================ S =============================================
	"":["sacrifice"],
	"":["sad but good"],
	"":["samurai"],
	"":["san francisco", "california"],
	"":["sappy"],
	"":["sarcasm"],
	"":["saturday night live"],
	"":["scary"],
	"":["scenic"],
	"":["schizophrenia"],
	"":["school"],
	"genres:'Sci-Fi'":["sci fi", "sci-fi", "scifi", "science fiction"],
	"":["science"],
	"":["scifi cult"],
	"":["scotland"],
	"":["screwball"],
	"":["screwball comedy"],
	"":["script"],
	"":["secret service"],
	"":["secrets"],
	"":["segregation"],
	"":["self discovery"],
	"":["sentimental"],
	"":["sequel", "sequels"],
	"":["serial killer"],
	"":["series"],
	"":["sex", "sexy", "erotic", "sexual", "sexuality"],
	"":["sex comedy"],
	"":["sexual abuse"],
	"":["sexualized violence"],
	"":["shakespeare"],
	"":["shallow"],
	"":["shark"],
	"":["shopping"],
	"":["short"],
	"":["short-term memory loss"],
	"":["silent"],
	"":["silly"],
	"":["silly fun"],
	"":["simple"],
	"":["single father"],
	"":["sisters"],
	"":["skinhead"],
	"":["slackers"],
	"":["slapstick"],
	"":["slasher"],
	"":["slavery"],
	"":["slow", "slow paced"],
	"":["small town"],
	"":["snakes"],
	"":["soccer"],
	"":["social commentary"],
	"":["solitude"],
	"":["sophia coppola"],
	"cast:'Sophia Copolla'":["sophia coppola"],
	"crew:'Sophia Copolla'":["sophia coppola"],
	"":["south africa"],
	"":["south america"],
	"":["southern theme"],
	"":["space"],
	"":["space opera"],
	"":["space program"],
	"":["space travel"],
	"":["spaghetti western"],
	"":["spain"],
	"":["spanish"],
	"":["spanish civil war"],
	"":["special"],
	"":["special effects"],
	"":["spelling bee"],
	"":["spiders"],
	"":["spielberg"],
	"crew:'Steven Spielberg'":["spielberg"],
	"":["spies"],
	"":["splatter"],
	"":["star trek", "spock"],
	"*title:Star Trek":["star trek", "spock"],
	"genres:'Sport'":["sports"],
	"":["spy", "espionage", "spying"],
	"":["stage magic"],
	"":["stand-up comedy"],
	"":["star wars"],
	"*title:Star Wars":["star wars"],
	"":["steampunk"],
	"":["stereotypes"],
	"":["stoner movie"],
	"":["stop motion", "stop-motion"],
	"":["storytelling"],
	"":["strange"],
	"":["strippers"],
	"":["stunning"],
	"":["stupidity"],
	"":["stylish"],
	"":["stylized"],
	"":["submarine"],
	"":["suburbia"],
	"":["suicide", "suicide attempt"],
	"":["super hero", "super-hero", "superhero", "superheroes"],
	"":["supernatural"],
	"":["suprisingly clever"],
	"":["surfing"],
	"":["surprise ending"],
	"":["surreal", "surrealism", "dreamlike"],
	"":["surveillance"],
	"":["survival"],
	"":["suspense", "suspenseful"],
	"":["swedish"],
	"country:'Sweden'":["swedish"],
	"":["sweet"],
	"":["switching places"],
	"":["sword fight", "sword fighting"],

	#============================================ T =============================================
	"":["talky"],
	"":["tarantino"],
	"crew:'Quentin Tarantino'":["tarantino"],
	"":["teacher"],
	"":["tear jerker"],
	"":["technology"],
	"":["teen", "teenager", "teenagers", "teens"],
	"":["teen movie"],
	"":["teleportation"],
	"":["television"],
	"":["tense"],
	"":["terminal illness"],
	"":["terrorism"],
	"":["texas"],
	"":["thought-provoking"],
	"genres:'Thriller'":["thriller"],
	"":["time"],
	"":["time loop"],
	"":["time travel"],
	"":["tokyo", "japan", "japanese"],
	"":["tolkien"],
	"":["tom clancy"],
	"crew:'Tom Clancy'":["tom clancy"]
	"":["torture"],
	"":["touching"],
	"":["toys"],
	"":["tragedy"],
	"":["train", "trains"],
	"":["transformation"],
	"":["transgender"],
	"":["travel"],
	"":["treasure", "treasure hunt"],
	"":["tricky"],
	"":["trilogy"],
	"":["true story"],
	"":["truman capote"],
	"crew:'Truman Capote'":["truman capote"],
	"":["twist", "twist ending"],
	"":["twists & turns"],

	#============================================ U =============================================
	"undercover-cop":["undercover cop"],
	"undercover-police":["undercover cop"],
	"undercover-policeman":["undercover cop"],
	"undercover-policewoman":["undercover cop"],
	"*underdog":["underdog"],
	"*underwater":["underwater"],
	"*united-nations":["united nations"],
	"american-history":["us history"],
	"*utopia":["utopia"],

	#============================================ V =============================================
	"virtual-reality":["virtual reality"],
	"virtual-set":["virtual reality"],
	"virtuality":["virtual reality"],
	"virtual-world":["virtual reality"],
	"virtual":["virtual reality"],
	"virtual-reality-game":["virtual reality", "computer game", "video game", "video games", "videogame"],
	"virtual-life":["virtual reality"],
	"*vampire":["vampire", "vampires"],
	"*dracula":["vampire", "vampires"],
	"vampire-human-love":["vampire human love"],
	"vengeance":["vengeance"],
	"revenge":["vengeance"],
	"vienna-austria":["vienna"],
	"vietnam":["vietnam"],
	"country:'Vietnam'":["vietnam"],
	"vietnamese":["vietnam"],
	"*vigilant":["vigilante", "vigilantism", "justice"],
	"*virus":["virus"],
	"infection":["virus"],
	"*plague":["virus"],
	"*epidemic":["virus"],
	"*pandemic":["virus"],
	"contagious-disease":["virus"],
	"*contagious":["virus"],
	"*virgin":["virginity"],
	"*voodoo":["voodoo"],
	"black-magic":["voodoo"],
	"*witchcraft":["voodoo"],
	"*curse":["voodoo"],
	"*voyeur":["voyeurism"],

	#============================================ W =============================================
	"genres:'War'":["war", "war movie", "wartime"],
	"world-war-two":["wwii", "world war ii"],
	"world-war-one":["world war i"],
	"cold-war-era":["cold war"],
	"*civil-war":["civil war"],
	"cold-war":["cold war"],
	"*vietnam-war":["vietnam war"],
	"vietnam-veteran":["vietnam war"],
	"vietnam-vet":["vietnam war"],
	"vietnam-flashback":["vietnam war"],
	"vietnam-memorial":["vietnam war"],
	"vietnamese-soldier":["vietnam war"],
	"american-civil-war":["american civil war"],
	"weapon":["weapons"],
	"*wedding":["wedding"],
	"weed":["weed", "drugs", "marijuana"],
	"smoking-weed":["weed", "drugs", "marijuana"],
	"*marijuana":["weed", "drugs", "marijuana"],
	"*cocaine":["weed", "drugs", "marijuana"],
	"methamphetamine":["weed", "drugs", "marijuana"],
	"crystal-meth":["weed", "drugs", "marijuana"],
	"meth":["weed", "drugs", "marijuana"],
	"meth-lab":["weed", "drugs", "marijuana"],
	"heroin":["weed", "drugs", "marijuana"],
	"*heroin-":["weed", "drugs", "marijuana"],
	"*drug":["weed", "drugs", "marijuana"],
	"*werewolf":["werewolf", "werewolves"],
	"genres:'Western'":["western"],
	"*witch":["witch", "witches"],
	"*wizard":["wizards"],
	"*working-class":["working class"],
	"*workplace":["workplace"],
	"*politic":["world politics", "political", "politics"],
	"*writer":["writers", "writing", "writer's life"],

	#============================================ Z =============================================
	"*zombie":["zombie", "zombies"]
}


# IMDB Keywords that should be ignored while processing the given wildcard filters.
# Values with a * in front should ignore all keywords that contain that value as a substring.
#
#	For example, in the dictionary above we have:
#		"*dragon":["dragon", "dragons"]
#
#	While in the dictionary below we have:
#		"*dragon":["*dragonfly"]
#
#	Thus when pairing IMDB keywords with the substring "dragon" with the ["dragon"/"dragons"] tag, you
#   should skip all keywords that have the substring "dragonfly".

imdbIgnore = {
	"*abus":["substance-abuse", "alcohol-abuse", "drug-abuse", "prescription-drug-abuse", "abuse-of-power"]
	"*alien":["*illegal-alien"],
	"*autis":["flautist"],
	"*aviat":["aviator-sunglasses", "*la-traviata"],
	"*berlin":["oberlin", "reference-to-frederick-george-abberline", "*irving-berlin"],
	"*buddy":["*reference-to-buddy"],
	"*chess":["*duchess"],
	"*cruise":["*cruise-missle", "*cruiser", "reference-to-tom-cruise"],
	"*-ship":["*space-ship", "*rocket-ship", "*shipment", "alien-ship"],
	"*christian":["hans-christian-andersen"],
	"*clon":["*cyclon", "insection-clone", "batman-clone", "mortal-combat-clone", "clonskeagh-dublin", "doom-clone", "leisure-suit-larry-clone", "tex-murphy-clone", "reference-to-saint-brendan-the-navigator-of-clonfert"]
	"*computer":["*computer-animat"],
	"*cook":["*cookie"],
	"*creepy":["creepy-crawlie"],
	"*cuba":["*scuba", "*incubat"],
	"*curse":["curse-word"],
	"*desert":["*desertion", "*deserted", "*desert-island", "*desert-eagle"],
	"*demon":["*demonst", "*pandemon"],
	"*devil":["*vaudeville", "*tasmanian-devil"],
	"*depress":["economic-depression", "*great-depression", "*depression-era", "depression-of-1929", "*depressor"],
	"*dog":["*dog-tag", "*dogfight", "*dog-fight", "*underdog", "*doggystyle", "*hot-dog", "*dogme", "*dogma", "*prairie-dog"],
	"*dream":["dream-girl", "dream-woman", "dream-job", "dream-house", "dream-home", "*dreamcast", "*dreamy"],
	"*drug":["*drugstore"],
	"*dragon":["*dragonfly"],
	"*french":["*french-kiss", "*french-accent"]
	"*hypno":["*rohypnol"],
	"*horror":["b-horror"],
	"*fight":["*firefight", "*fire-fight", "*fighter-jet", "*food-fight", "*fighter-pilot", "*dogfight", "*dog-fight", "*pillow-fight", "fight-the-system", "*bullfight", "*bull-fight", "*cockfight", "*cock-fight", "*snowball-fight"],
	"*jazz":["jazz-the-character"],
	"*jewish":["jewish-stereotype", "jewish-slur"],
	"*protest":["*protestant"],
	"*robot":["ostrobothnia-finland"],
	"*witch":["*switch", "*twitch"],
	"*virgin":["*virginia", "*virgin-mary"]
}